const sqlite3 = require('sqlite3');
const logger = require("./Log").getLogger(__filename);

const DB = new sqlite3.cached.Database("./constants.sqlite", sqlite3.OPEN_READONLY);

const townstrings = [
  "Lioneye's Watch",
  "The Forest Encampment",
  "The Sarn Encampment",
  "Highgate",
  "Overseer's Tower",
  "The Bridge Encampment",
  "Oriath Docks",
  "Oriath",
  "The Templar Laboratory",
  "Crumbled Laboratory",
  "Hideout"
];

const labAreas = [
  "Aspirants' Plaza",
  "Sepulchre Annex",
  "Sepulchre Passage",
  "Sepulchre Halls",
  "Sepulchre Atrium",
  "Sanitorium Annex",
  "Sanitorium Passage",
  "Sanitorium Halls",
  "Sanitorium Atrium",
  "Mansion Annex",
  "Mansion Passage",
  "Mansion Halls",
  "Mansion Atrium",
  "Basilica Annex",
  "Basilica Passage",
  "Basilica Halls",
  "Basilica Atrium",
  "Domain Enclosure",
  "Domain Path",
  "Domain Walkways",
  "Domain Crossing",
  "Estate Enclosure",
  "Estate Path",
  "Estate Walkways",
  "Estate Crossing"
];

const uniqueMaps = {
  "Chateau Map": "The Perandus Manor",
  "Museum Map": "The Putrid Cloister",
  "Moon Temple Map": "The Twilight Temple",
  "Courtyard Map": "The Vinktar Square",
  "Temple Map": "Poorjoy's Asylum",
  "Shore Map": "Mao Kun",
  "Promenade Map": "Hall of Grandmasters",
  "Torture Chamber Map": "Oba's Cursed Trove",
  "Vaal Pyramid Map": "Vaults of Atziri",
  "Cursed Crypt Map": "The Coward's Trial",
  "Underground River Map": "Caer Blaidd, Wolfpack's Den",
  "Cemetery Map": "Hallowed Ground",
  "Bone Crypt Map": "Olmec's Sanctum",
  "Overgrown Shrine Map": "Acton's Nightmare",
  "Necropolis Map": "Death and Taxes",
  "Dunes Map": "Pillars of Arun",
  "Atoll Map": "Maelstr�m of Chaos",
  "Strand Map": "Whakawairua Tuahu"
};

const baseMaps = [
  "Arcade Map",
  "Crystal Ore Map",
  "Desert Map",
  "Jungle Valley Map",
  "Beach Map",
  "Factory Map",
  "Ghetto Map",
  "Oasis Map",
  "Arid Lake Map",
  "Cavern Map",
  "Channel Map",
  "Grotto Map",
  "Marshes Map",
  "Sewer Map",
  "Vaal Pyramid Map",
  "Academy Map",
  "Acid Lakes Map",
  "Dungeon Map",
  "Graveyard Map",
  "Phantasmagoria Map",
  "Villa Map",
  "Waste Pool Map",
  "Burial Chambers Map",
  "Dunes Map",
  "Mesa Map",
  "Peninsula Map",
  "Pit Map",
  "Primordial Pool Map",
  "Spider Lair Map",
  "Tower Map",
  "Canyon Map",
  "Quarry Map",
  "Racecourse Map",
  "Ramparts Map",
  "Spider Forest Map",
  "Strand Map",
  "Thicket Map",
  "Vaal City Map",
  "Wharf Map",
  "Arachnid Tomb Map",
  "Armoury Map",
  "Ashen Wood Map",
  "Castle Ruins Map",
  "Catacombs Map",
  "Cells Map",
  "Mud Geyser Map",
  "Arachnid Nest Map",
  "Arena Map",
  "Atoll Map",
  "Barrows Map",
  "Bog Map",
  "Cemetery Map",
  "Pier Map",
  "Shore Map",
  "Tropical Island Map",
  "Coves Map",
  "Crypt Map",
  "Museum Map",
  "Orchard Map",
  "Overgrown Shrine Map",
  "Promenade Map",
  "Reef Map",
  "Temple Map",
  "Arsenal Map",
  "Colonnade Map",
  "Courtyard Map",
  "Malformation Map",
  "Port Map",
  "Terrace Map",
  "Underground River Map",
  "Bazaar Map",
  "Chateau Map",
  "Excavation Map",
  "Precinct Map",
  "Torture Chamber Map",
  "Underground Sea Map",
  "Wasteland Map",
  "Crematorium Map",
  "Estuary Map",
  "Ivory Temple Map",
  "Necropolis Map",
  "Plateau Map",
  "Residence Map",
  "Shipyard Map",
  "Vault Map",
  "Beacon Map",
  "Gorge Map",
  "High Gardens Map",
  "Lair Map",
  "Plaza Map",
  "Scriptorium Map",
  "Sulphur Wastes Map",
  "Waterways Map",
  "Maze Map",
  "Mineral Pools Map",
  "Palace Map",
  "Shrine Map",
  "Springs Map",
  "Volcano Map",
  "Abyss Map",
  "Colosseum Map",
  "Core Map",
  "Dark Forest Map",
  "Overgrown Ruin Map",
  "Forge of the Phoenix Map",
  "Lair of the Hydra Map",
  "Maze of the Minotaur Map",
  "Pit of the Chimera Map",
  "Vaal Temple Map",
  "Sunken City Map",
  "Basilica Map",
  "Crimson Temple Map",
  "Defiled Cathedral Map",
  "Park Map",
  "Carcass Map",
  "Caldera Map",
  "Desert Spring Map",
  "Dig Map",
  "Sepulchre Map",
  "Siege Map",
  "Summit Map",
  "Mausoleum Map",
  "Lava Lake Map",
  "Laboratory Map",
  "Bone Crypt Map",
  "Lava Chamber Map",
  "Cursed Crypt Map",
  "Toxic Sewer Map",
  "Lookout Map",
  "Pen Map",
  "Alleyways Map",
  "Cage Map",
  "Courthouse Map",
  "Flooded Mine Map",
  "Sulphur Vents Map",
  "City Square Map",
  "Leyline Map",
  "Conservatory Map",
  "Coral Ruins Map",
  "Haunted Mansion Map",
  "Relic Chambers Map",
  "Infested Valley Map",
  "Iceberg Map",
  "Lighthouse Map",
  "Gardens Map",
  "Tribunal Map",
  "Geode Map",
  "Ancient City Map",
  "Fields Map",
  "Moon Temple Map",
  "Belfry Map"
];

const areas = [
  // story mode areas
  "The Twilight Strand",
  "The Coast",
  "The Tidal Island",
  "The Mud Flats",
  "The Fetid Pool",
  "The Submerged Passage",
  "The Flooded Depths",
  "The Ledge",
  "The Climb",
  "The Lower Prison",
  "The Upper Prison",
  "Prisoner's Gate",
  "The Ship Graveyard",
  "The Ship Graveyard Cave",
  "The Cavern of Wrath",
  "The Cavern of Anger",
  "The Southern Forest",
  "The Old Fields",
  "The Den",
  "The Riverways",
  "The Crossroads",
  "The Chamber of Sins Level 1",
  "The Chamber of Sins Level 2",
  "The Broken Bridge",
  "The Fellshrine Ruins",
  "The Crypt Level 1",
  "The Crypt Level 2",
  "The Western Forest",
  "The Weaver's Chambers",
  "The Wetlands",
  "The Vaal Ruins",
  "The Northern Forest",
  "The Dread Thicket",
  "The Caverns",
  "The Ancient Pyramid",
  "The City of Sarn",
  "The Slums",
  "The Crematorium",
  "The Sewers",
  "The Marketplace",
  "The Catacombs",
  "The Battlefront",
  "The Solaris Temple Level 1",
  "The Solaris Temple Level 2",
  "The Docks",
  "The Ebony Barracks",
  "The Lunaris Temple Level 1",
  "The Lunaris Temple Level 2",
  "The Imperial Garden",
  "The Library",
  "The Archives",
  "The Hedge Maze",
  "The Sceptre of God",
  "The Upper Sceptre of God",
  "The Aqueduct",
  "The Dried Lake",
  "The Mines Level 1",
  "The Mines Level 2",
  "The Crystal Veins",
  "Daresso's Dream",
  "The Grand Arena",
  "Kaom's Dream",
  "Kaom's Stronghold",
  "The Belly of the Beast Level 1",
  "The Belly of the Beast Level 2",
  "The Harvest",
  "The Ascent",
  "The Slave Pens",
  "The Control Blocks",
  "Oriath Square",
  "The Templar Courts",
  "The Chamber of Innocence",
  "The Torched Courts",
  "The Ruined Square",
  "The Ossuary",
  "The Reliquary",
  "The Cathedral Rooftop",
  "The Twilight Strand",
  "The Coast",
  "The Tidal Island",
  "The Mud Flats",
  "The Karui Fortress",
  "The Ridge",
  "The Lower Prison",
  "Shavronne's Tower",
  "Prisoner's Gate",
  "The Western Forest",
  "The Riverways",
  "The Wetlands",
  "The Southern Forest",
  "The Cavern of Anger",
  "The Beacon",
  "The Brine King's Reef",
  "The Broken Bridge",
  "The Crossroads",
  "The Fellshrine Ruins",
  "The Crypt",
  "The Chamber of Sins Level 1",
  "The Chamber of Sins Level 2",
  "Maligaro's Sanctum",
  "The Den",
  "The Ashen Fields",
  "The Northern Forest",
  "The Dread Thicket",
  "The Causeway",
  "The Vaal City",
  "The Temple of Decay Level 1",
  "The Temple of Decay Level 2",
  "The Sarn Ramparts",
  "The Toxic Conduits",
  "Doedre's Cesspool",
  "The Grand Promenade",
  "The Quay",
  "The Grain Gate",
  "The Imperial Fields",
  "The Solaris Temple Level 1",
  "The Solaris Temple Level 2",
  "The Solaris Concourse",
  "The Bath House",
  "The High Gardens",
  "The Lunaris Concourse",
  "The Lunaris Temple Level 1",
  "The Lunaris Temple Level 2",
  "The Harbour Bridge",
  "The Blood Aqueduct",
  "The Descent",
  "The Vastiri Desert",
  "The Oasis",
  "The Foothills",
  "The Boiling Lake",
  "The Tunnel",
  "The Quarry",
  "The Refinery",
  "The Belly of the Beast",
  "The Rotting Core",
  "The Cathedral Rooftop",
  "The Ravaged Square",
  "The Torched Courts",
  "The Desecrated Chambers",
  "The Ossuary",
  "The Reliquary",
  "The Canals",
  "The Feeding Trough",
  "Aspirants' Plaza",
  // vaal side areas
  "Abandoned Dam",
  "Ancient Catacomb",
  "Arcane Chambers",
  "Blind Alley",
  "Clouded Ledge",
  "Clouded Ridge",
  "Concealed Caldarium",
  "Concealed Cavity",
  "Covered-up Hollow",
  "Cremated Archives",
  "Deathly Chambers",
  "Desolate Isle",
  "Desolate Track",
  "Disused Furnace",
  "Dusty Bluff",
  "Entombed Alcove",
  "Entombed Chamber",
  "Evacuated Quarter",
  "Flooded Complex",
  "Forbidden Archives",
  "Forbidden Chamber",
  "Forbidden Shrine",
  "Forgotten Conduit",
  "Forgotten Gulch",
  "Forgotten Oubliette",
  "Haunted Mineshaft",
  "Hidden Patch",
  "Inner Grounds",
  "Moonlit Chambers",
  "Mystical Clearing",
  "Narrow Ravine",
  "Neglected Cellar",
  "Quarantined Quarters",
  "Radiant Pools",
  "Reclaimed Barracks",
  "Remote Gulch",
  "Restricted Collection",
  "Restricted Gallery",
  "Sacred Chambers",
  "Sealed Basement",
  "Sealed Corridors",
  "Sealed Repository",
  "Secluded Canal",
  "Secluded Copse",
  "Secret Laboratory",
  "Shifting Sands",
  "Side Chapel",
  "Stagnant Canal",
  "Strange Sinkhole",
  "Sunken Shingle",
  "Twisted Inquisitorium",
  "Walled-off Ducts",
  // pre-3.1 maps
  "Arcade",
  "Crystal Ore",
  "Desert",
  "Jungle Valley",
  "Beach",
  "Factory",
  "Ghetto",
  "Oasis",
  "Esh's Domain",
  "Tul's Domain",
  "Xoph's Domain",
  "The Apex of Sacrifice",
  "Arid Lake",
  "Cavern",
  "Channel",
  "Grotto",
  "Marshes",
  "Sewer",
  "Vaal Pyramid",
  "Vaults of Atziri",
  "Academy",
  "Acid Lakes",
  "Dungeon",
  "Graveyard",
  "Hallowed Ground",
  "Phantasmagoria",
  "Villa",
  "Waste Pool",
  "Burial Chambers",
  "The Beachhead",
  "Dunes",
  "Mesa",
  "Peninsula",
  "Pit",
  "Primordial Pool",
  "Spider Lair",
  "Tower",
  "Canyon",
  "Quarry",
  "Racecourse",
  "Ramparts",
  "Spider Forest",
  "Strand",
  "Whakawairua Tuahu",
  "Thicket",
  "Vaal City",
  "Wharf",
  "Arachnid Tomb",
  "Armoury",
  "Ashen Wood",
  "Castle Ruins",
  "Catacombs",
  "Olmec's Sanctum",
  "Cells",
  "Mud Geyser",
  "Uul-Netol's Domain",
  "The Pale Court",
  "Arachnid Nest",
  "Arena",
  "Atoll",
  "Maelstrom of Chaos",
  "Barrows",
  "Bog",
  "Cemetery",
  "The Eternal Labyrinth",
  "Pier",
  "Shore",
  "Tropical Island",
  "Untainted Paradise",
  "Coves",
  "Crypt",
  "The Coward's Trial",
  "Museum",
  "The Putrid Cloister",
  "Orchard",
  "Overgrown Shrine",
  "Acton's Nightmare",
  "Promenade",
  "The Hall of Grandmasters",
  "Reef",
  "Mao Kun",
  "Temple",
  "Poorjoy's Asylum",
  "Arsenal",
  "Colonnade",
  "Courtyard",
  "The Vinktar Square",
  "Malformation",
  "Port",
  "Terrace",
  "Underground River",
  "Caer Blaidd, Wolfpack's Den",
  "Bazaar",
  "Chateau",
  "The Perandus Manor",
  "Excavation",
  "Precinct",
  "Torture Chamber",
  "Oba's Cursed Trove",
  "Underground Sea",
  "Wasteland",
  "Crematorium",
  "Estuary",
  "Ivory Temple",
  "Necropolis",
  "Death and Taxes",
  "Plateau",
  "Residence",
  "Shipyard",
  "Vault",
  "The Alluring Abyss",
  "Chayula's Domain",
  "Beacon",
  "Gorge",
  "High Gardens",
  "Lair",
  "Plaza",
  "Scriptorium",
  "Sulphur Wastes",
  "Waterways",
  "Maze",
  "Mineral Pools",
  "Palace",
  "Shrine",
  "Springs",
  "Volcano",
  "Abyss",
  "Colosseum",
  "Core",
  "Dark Forest",
  "Overgrown Ruin",
  "Forge of the Phoenix",
  "Lair of the Hydra",
  "Maze of the Minotaur",
  "Pit of the Chimera",
  "Vaal Temple ",
  "The Apex of Sacrifice",
  "The Pale Court",
  "The Alluring Abyss",
  "The Shaper's Realm",
  // 3.1 maps
  "The Twilight Temple",
  "Sunken City",
  "Basilica",
  "Crimson Temple",
  "Defiled Cathedral",
  "Park",
  "Carcass",
  "Caldera",
  "Desert Spring",
  "Dig",
  "Sepulchre",
  "Siege",
  "Summit",
  "Mausoleum",
  "Lava Lake",
  "Laboratory",
  "Bone Crypt",
  "Lava Chamber",
  "Cursed Crypt",
  "Toxic Sewer",
  "Lookout",
  "Pen",
  "Alleyways",
  "Cage",
  "Courthouse",
  "Flooded Mine",
  "Sulphur Vents",
  "City Square",
  "Leyline",
  "Conservatory",
  "Coral Ruins",
  "Haunted Mansion",
  "Relic Chambers",
  "Infested Valley",
  "Iceberg",
  "Lighthouse",
  "Gardens",
  "Tribunal",
  "Geode",
  "Ancient City",
  "Fields",
  "Pillars of Arun",
  "Moon Temple",
  "Belfry",
  // 3.3
  "The Temple of Atzoatl",
  // 3.4
  "Doryani's Machinarium",
  // Delve
  "Azurite Mine",
  // lab
  "Sepulchre Annex",
  "Sepulchre Passage",
  "Sepulchre Halls",
  "Sepulchre Atrium",
  "Sanitorium Annex",
  "Sanitorium Passage",
  "Sanitorium Halls",
  "Sanitorium Atrium",
  "Mansion Annex",
  "Mansion Passage",
  "Mansion Halls",
  "Mansion Atrium",
  "Basilica Annex",
  "Basilica Passage",
  "Basilica Halls",
  "Basilica Atrium",
  "Domain Enclosure",
  "Domain Path",
  "Domain Walkways",
  "Domain Crossing",
  "Estate Enclosure",
  "Estate Path",
  "Estate Walkways",
  "Estate Crossing"
];

const mods = [
  "#% increased Experience gain",
  "#% increased Monster Attack Speed",
  "#% increased Monster Cast Speed",
  "#% increased Monster Damage",
  "#% increased Monster Movement Speed",
  "#% increased Quantity of Items found in this Area",
  "#% increased Rarity of Items found in this Area",
  "-#% maximum Player Resistances",
  "#% more Magic Monsters",
  "#% more Monster Life",
  "#% more Rare Monsters",
  "+#% Monster Cold Resistance",
  "+#% Monster pack size",
  "+#% to Monster Critical Strike Multiplier",
  "+#% Monster Chaos Resistance",
  "+#% Monster Elemental Resistance",
  "+#% Monster Fire Resistance",
  "+#% Monster Lightning Resistance",
  "+#% Monster Cold Resistance",
  "+#% Monster Physical Damage Reduction",
  "0.5 Flask Charges recovered every 3 seconds",
  "100% increased effect of Onslaught on Players and Monsters",
  "15% increased Pack Size in Unidentified Maps",
  "20% increased Player and Monster Movement Speed",
  "30% increased Magic Pack Size",
  "30% increased Quantity of Items found in Unidentified Maps",
  "20% reduced Effect of Curses on Monsters",
  "#% less effect of Curses on Monsters",
  "60% reduced Effect of Curses on Players",
  "All Monster Damage from Hits always Ignites",
  "An additional Map drops on Completing Area",
  "Arctic Tempest",
  "Area becomes fatal after some time",
  "Area can contain Mysterious Harbingers",
  "Area contains # additional Breaches",
  "Area contains # additional Essences",
  "Area contains # additional Perandus Chests",
  "Area contains # extra Harbingers",
  "Area contains # extra Shrines",
  "Area contains # extra Strongboxes",
  "Area contains 30 additional Clusters of Mysterious Barrels",
  "Area contains a Large Chest",
  "Area contains a Voidspawn of Abaxoth Bloodline Pack",
  "Area contains additional Magic Monsters",
  "Area contains additional Monsters that Convert when Killed",
  "Area contains additional Monsters that deal Chaos Damage",
  "Area contains additional Monsters that deal Cold Damage",
  "Area contains additional Monsters that deal Fire Damage",
  "Area contains additional Monsters that deal Lightning Damage",
  "Area contains additional Monsters that deal Physical Damage",
  "Area contains additional Monsters that Heal",
  "Area contains additional Normal Monsters",
  "Area contains additional Packs with Mirrored Rare Monsters",
  "Area contains additional Poisonous Monsters",
  "Area contains an additional Abyss",
  "Area contains an additional Breach",
  "Area contains an extra Strongbox",
  "Area contains Cadiro Perandus",
  "Area contains Catarina",
  "Area contains Elreon",
  "Area contains Haku",
  "Area contains Hunted Traitors",
  "Area contains many Totems",
  "Area contains no monsters",
  "Area contains Slipstreams",
  "Area contains Tora",
  "Area contains two Unique Bosses",
  "Area contains unbridged gaps to cross",
  "Area contains Vagan",
  "Area contains Vorici",
  "Area contains Zana",
  "Area has # seconds between monster waves",
  "Area has # waves of monsters",
  "Area has a #% chance to contain Cadiro Perandus",
  "Area has increased monster variety",
  "Area has patches of burning ground",
  "Area has patches of chilled ground",
  "Area has patches of desecrated ground",
  "Area has patches of shocking ground",
  "Area has patches of tar",
  "Area is a large Maze",
  "Area is Alluring",
  "Area is Corrupted",
  "Area is inhabited by # additional Rogue Exiles",
  "Area is inhabited by 1 additional Warband",
  "Area is inhabited by # additional Warbands",
  "Area is inhabited by 1 additional Rogue Exile",
  "Area is inhabited by Abominations",
  "Area is inhabited by an additional Invasion Boss",
  "Area is inhabited by Animals",
  "Area is inhabited by Demons",
  "Area is inhabited by Ghosts",
  "Area is inhabited by Goatmen",
  "Area is inhabited by Humanoids",
  "Area is inhabited by Lunaris fanatics",
  "Area is inhabited by ranged monsters",
  "Area is inhabited by Sea Witches and their Spawn",
  "Area is inhabited by Skeletons",
  "Area is inhabited by Solaris fanatics",
  "Area is inhabited by the Vaal",
  "Area is inhabited by Undead",
  "Area is inhabited by Wild Animals",
  "Area is Overgrown with Caustic Plants",
  "Area is Unidentified",
  "Areas can contain Abysses",
  "Areas can contain Breaches",
  "Areas can contain Essences",
  "Areas contain deposits of Voltaxic Sulphite",
  "Areas contain Temporal Incursions",
  "Cannot Leech Life from Monsters",
  "Cannot Leech Mana from Monsters",
  "Chests have #% increased Item Rarity",
  "Contains the Immortalised Grandmasters",
  "Crushing Tempest",
  "Electrocuting Tempest",
  "Final Boss drops higher Level Items",
  "Found Items drop Identified in Area",
  "Found Items have a 10% chance to drop Corrupted in Area",
  "Found Items have a 5% chance to drop Corrupted in Area",
  "Infernal Tempest",
  "Items dropped by Unique Bosses are Corrupted",
  "Magic Monster Packs each have a Bloodline Mod",
  "Map has 20% Quality",
  "Minimap is Revealed",
  "Monster Level: #",
  "Monsters are Hexproof",
  "Monsters are Immune to randomly chosen Elemental Ailments or Stun",
  "Monsters cannot be Shocked",
  "Monsters cannot be slowed below base speed",
  "Monsters cannot be Stunned",
  "Monsters cannot be Taunted",
  "Monsters deal #% extra Damage as Cold",
  "Monsters deal #% extra Damage as Fire",
  "Monsters deal #% extra Damage as Lightning",
  "Monsters drop no items",
  "Monsters fire 2 additional Projectiles",
  "Monsters gain 3 Endurance Charges every 20 seconds",
  "Monsters gain 3 Power Charges every 20 seconds",
  "Monsters gain a Frenzy Charge on Hit",
  "Monsters gain a Power Charge on Hit",
  "Monsters gain an Endurance Charge on Hit",
  "Monsters have #% chance to Avoid Ailments",
  "Monsters have #% increased Critical Strike Chance",
  "Monsters have #% increased Area of Effect",
  "Monsters have #% increased Accuracy Rating",
  "Monsters have #% chance to Avoid Elemental Ailments",
  "Monsters have a #% chance to cause Elemental Ailments on Hit",
  "Monsters have a #% chance to avoid Poison, Blind, and Bleeding",
  "Monsters have Onslaught",
  "Monsters' Melee Attacks apply random Curses on Hit",
  "Monsters Poison on Hit",
  "Monsters reflect #% of Elemental Damage",
  "Monsters reflect #% of Physical Damage",
  "Monsters reflect Curses",
  "Monsters' skills Chain 1 additional time",
  "Monsters' skills Chain 2 additional times",
  "Monsters' skills Chain 3 additional times",
  "Monsters take #% reduced Extra Damage from Critical Strikes",
  "Morbid Tempest",
  "Mysterious Harbingers roam Wraeclast and Oriath",
  "Nemesis Monsters drop 3 additional Currency Items",
  "Non-Unique Monsters in this Area Regenerate #% of Maximum Life per second",
  "Player Dodge chance is Unlucky",
  "Players and Monsters have Onslaught if they have been Hit Recently",
  "Players and Monsters take 10% increased Chaos Damage",
  "Players and Monsters take 10% increased Cold Damage",
  "Players and Monsters take 10% increased Fire Damage",
  "Players and Monsters take 10% increased Lightning Damage",
  "Players and Monsters take 10% increased Physical Damage",
  "Players are Cursed with Elemental Weakness",
  "Players are Cursed with Enfeeble",
  "Players are Cursed with Flammability",
  "Players are Cursed with Frostbite",
  "Players are Cursed with Temporal Chains",
  "Players are Cursed with Vulnerability",
  "Players cannot Regenerate Life, Mana or Energy Shield",
  "Players cannot take Reflected Damage",
  "Players deal 10% increased Damage for each Poison on them",
  "Players deal 100% increased Damage while stationary",
  "Players gain #% reduced Flask Charges",
  "Players have #% less Area of Effect",
  "Players have #% less Armour",
  "Players have #% less Recovery Rate of Life and Energy Shield",
  "Players have #% reduced Chance to Block",
  "Players have 200% increased Cooldown Recovery Speed for Movement Skills",
  "Players have 5% increased Movement Speed for each Poison on them",
  "Players have Elemental Equilibrium",
  "Players have Point Blank",
  "Player's Life and Mana Recovery from Flasks are instant",
  "Players take 10% increased Damage while stationary",
  "PvP damage scaling in effect",
  "Rare Monsters each have a Nemesis Mod",
  "Restless Dead",
  "Rogue Exiles deal 20% increased Damage",
  "Rogue Exiles drop 2 additional Jewels",
  "Rogue Exiles have 20% increased Maximum Life",
  "Slaying Enemies close together can attract monsters from Beyond",
  "Strongbox Monsters are Enraged",
  "Strongbox Monsters have 500% increased Item Quantity",
  "Strongboxes in Areas are at least Rare Rarity",
  "Strongboxes in Areas are Corrupted",
  "This Area's Modifiers to Quantity of Items found also apply to Rarity",
  "This Map's Quality also applies to Rarity of Items found",
  "Unique Boss deals #% increased Damage",
  "Unique Boss drops # additional Rare Amulets",
  "Unique Boss drops # additional Rare Belts",
  "Unique Boss drops # additional Rare Body Armours",
  "Unique Boss drops # additional Rare Boots",
  "Unique Boss drops # additional Rare Bows",
  "Unique Boss drops # additional Rare Claws",
  "Unique Boss drops # additional Rare Daggers",
  "Unique Boss drops # additional Rare Gloves",
  "Unique Boss drops # additional Rare Helmets",
  "Unique Boss drops # additional Rare One-Handed Axes",
  "Unique Boss drops # additional Rare One-Handed Maces",
  "Unique Boss drops # additional Rare One-Handed Swords",
  "Unique Boss drops # additional Rare One-Handed Thrusting Swords",
  "Unique Boss drops # additional Rare Quivers",
  "Unique Boss drops # additional Rare Rings",
  "Unique Boss drops # additional Rare Sceptres",
  "Unique Boss drops # additional Rare Shields",
  "Unique Boss drops # additional Rare Staves",
  "Unique Boss drops # additional Rare Two-Handed Axes",
  "Unique Boss drops # additional Rare Two-Handed Maces",
  "Unique Boss drops # additional Rare Two-Handed Swords",
  "Unique Boss drops # additional Rare Wands",
  "Unique Boss drops 1 additional Unique Item",
  "Unique Boss drops # additional Maps",
  "Unique Boss drops an additional Vaal Item",
  "Unique Boss gives #% increased Experience",
  "Unique Boss has #% increased Attack and Cast Speed",
  "Unique Boss has #% increased Life",
  "Unique Boss has #% increased Area of Effect",
  "Unique Boss is accompanied by Bodyguards",
  "Unique Monsters drop Corrupted Items"
];

function getItemName(icon) {
  logger.info("Getting name for " + icon);
  return new Promise( (resolve, reject) => {
    DB.get(" select name from itemicons where icon = ? and upgraded = 0 ", [icon], (err, row) => {
      if(!row) {
        resolve();
      } else {
        resolve(row.name);
      }
    });
  });
}

module.exports.townstrings = townstrings;
module.exports.uniqueMaps = uniqueMaps;
module.exports.baseMaps = baseMaps;
module.exports.areas = areas;
module.exports.labAreas = labAreas;
module.exports.mods = mods;
module.exports.DB = DB;
module.exports.getItemName = getItemName;