const logger = require("./Log").getLogger(__filename);

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

const equipmentBaseTypes = {
  "Hypnotic Eye Jewel" : "Abyss Jewel",
  "Murderous Eye Jewel" : "Abyss Jewel",
  "Searching Eye Jewel" : "Abyss Jewel",
  "Ghastly Eye Jewel" : "Abyss Jewel",
  "Blue Pearl Amulet" : "Amulets",
  "Jet Amulet" : "Amulets",
  "Marble Amulet" : "Amulets",
  "Paua Amulet" : "Amulets",
  "Ruby Amulet" : "Amulets",
  "Citrine Amulet" : "Amulets",
  "Coral Amulet" : "Amulets",
  "Amber Amulet" : "Amulets",
  "Jade Amulet" : "Amulets",
  "Lapis Amulet" : "Amulets",
  "Gold Amulet" : "Amulets",
  "Onyx Amulet" : "Amulets",
  "Turquoise Amulet" : "Amulets",
  "Agate Amulet" : "Amulets",
  "Black Maw Talisman" : "Amulets",
  "Mandible Talisman" : "Amulets",
  "Chrysalis Talisman" : "Amulets",
  "Writhing Talisman" : "Amulets",
  "Bonespire Talisman" : "Amulets",
  "Ashscale Talisman" : "Amulets",
  "Lone Antler Talisman" : "Amulets",
  "Deep One Talisman" : "Amulets",
  "Breakrib Talisman" : "Amulets",
  "Deadhand Talisman" : "Amulets",
  "Undying Flesh Talisman" : "Amulets",
  "Rot Head Talisman" : "Amulets",
  "Hexclaw Talisman" : "Amulets",
  "Primal Skull Talisman" : "Amulets",
  "Wereclaw Talisman" : "Amulets",
  "Splitnewt Talisman" : "Amulets",
  "Clutching Talisman" : "Amulets",
  "Avian Twins Talisman" : "Amulets",
  "Fangjaw Talisman" : "Amulets",
  "Horned Talisman" : "Amulets",
  "Spinefuse Talisman" : "Amulets",
  "Three Rat Talisman" : "Amulets",
  "Monkey Twins Talisman" : "Amulets",
  "Longtooth Talisman" : "Amulets",
  "Rotfeather Talisman" : "Amulets",
  "Monkey Paw Talisman" : "Amulets",
  "Three Hands Talisman" : "Amulets",
  "Greatwolf Talisman" : "Amulets",
  "Golden Obi" : "Belts",
  "Rustic Sash" : "Belts",
  "Chain Belt" : "Belts",
  "Leather Belt" : "Belts",
  "Heavy Belt" : "Belts",
  "Cloth Belt" : "Belts",
  "Studded Belt" : "Belts",
  "Stygian Vise" : "Belts",
  "Vanguard Belt" : "Belts",
  "Crystal Belt" : "Belts",
  "Shabby Jerkin" : "Body Armours",
  "Golden Mantle" : "Body Armours",
  "Glorious Leather" : "Body Armours",
  "Coronal Leather" : "Body Armours",
  "Cutthroat's Garb" : "Body Armours",
  "Sharkskin Tunic" : "Body Armours",
  "Destiny Leather" : "Body Armours",
  "Exquisite Leather" : "Body Armours",
  "Zodiac Leather" : "Body Armours",
  "Assassin's Garb" : "Body Armours",
  "Strapped Leather" : "Body Armours",
  "Buckskin Tunic" : "Body Armours",
  "Wild Leather" : "Body Armours",
  "Full Leather" : "Body Armours",
  "Sun Leather" : "Body Armours",
  "Thief's Garb" : "Body Armours",
  "Eelskin Tunic" : "Body Armours",
  "Frontier Leather" : "Body Armours",
  "Padded Vest" : "Body Armours",
  "Crimson Raiment" : "Body Armours",
  "Lacquered Garb" : "Body Armours",
  "Crypt Armour" : "Body Armours",
  "Sentinel Jacket" : "Body Armours",
  "Varnished Coat" : "Body Armours",
  "Blood Raiment" : "Body Armours",
  "Sadist Garb" : "Body Armours",
  "Carnal Armour" : "Body Armours",
  "Oiled Vest" : "Body Armours",
  "Padded Jacket" : "Body Armours",
  "Oiled Coat" : "Body Armours",
  "Scarlet Raiment" : "Body Armours",
  "Waxed Garb" : "Body Armours",
  "Bone Armour" : "Body Armours",
  "Quilted Jacket" : "Body Armours",
  "Sleek Coat" : "Body Armours",
  "Simple Robe" : "Body Armours",
  "Conjurer's Vestment" : "Body Armours",
  "Spidersilk Robe" : "Body Armours",
  "Destroyer Regalia" : "Body Armours",
  "Savant's Robe" : "Body Armours",
  "Necromancer Silks" : "Body Armours",
  "Occultist's Vestment" : "Body Armours",
  "Widowsilk Robe" : "Body Armours",
  "Vaal Regalia" : "Body Armours",
  "Silken Vest" : "Body Armours",
  "Scholar's Robe" : "Body Armours",
  "Silken Garb" : "Body Armours",
  "Mage's Vestment" : "Body Armours",
  "Silk Robe" : "Body Armours",
  "Cabalist Regalia" : "Body Armours",
  "Sage's Robe" : "Body Armours",
  "Silken Wrap" : "Body Armours",
  "Plate Vest" : "Body Armours",
  "Sun Plate" : "Body Armours",
  "Colosseum Plate" : "Body Armours",
  "Majestic Plate" : "Body Armours",
  "Golden Plate" : "Body Armours",
  "Crusader Plate" : "Body Armours",
  "Astral Plate" : "Body Armours",
  "Gladiator Plate" : "Body Armours",
  "Glorious Plate" : "Body Armours",
  "Chestplate" : "Body Armours",
  "Copper Plate" : "Body Armours",
  "War Plate" : "Body Armours",
  "Full Plate" : "Body Armours",
  "Arena Plate" : "Body Armours",
  "Lordly Plate" : "Body Armours",
  "Bronze Plate" : "Body Armours",
  "Battle Plate" : "Body Armours",
  "Scale Vest" : "Body Armours",
  "Full Wyrmscale" : "Body Armours",
  "Commander's Brigandine" : "Body Armours",
  "Battle Lamellar" : "Body Armours",
  "Dragonscale Doublet" : "Body Armours",
  "Desert Brigandine" : "Body Armours",
  "Full Dragonscale" : "Body Armours",
  "General's Brigandine" : "Body Armours",
  "Triumphant Lamellar" : "Body Armours",
  "Light Brigandine" : "Body Armours",
  "Scale Doublet" : "Body Armours",
  "Infantry Brigandine" : "Body Armours",
  "Full Scale Armour" : "Body Armours",
  "Soldier's Brigandine" : "Body Armours",
  "Field Lamellar" : "Body Armours",
  "Wyrmscale Doublet" : "Body Armours",
  "Hussar Brigandine" : "Body Armours",
  "Sacrificial Garb" : "Body Armours",
  "Chainmail Vest" : "Body Armours",
  "Ornate Ringmail" : "Body Armours",
  "Chain Hauberk" : "Body Armours",
  "Devout Chainmail" : "Body Armours",
  "Loricated Ringmail" : "Body Armours",
  "Conquest Chainmail" : "Body Armours",
  "Elegant Ringmail" : "Body Armours",
  "Saint's Hauberk" : "Body Armours",
  "Saintly Chainmail" : "Body Armours",
  "Chainmail Tunic" : "Body Armours",
  "Ringmail Coat" : "Body Armours",
  "Chainmail Doublet" : "Body Armours",
  "Full Ringmail" : "Body Armours",
  "Full Chainmail" : "Body Armours",
  "Holy Chainmail" : "Body Armours",
  "Latticed Ringmail" : "Body Armours",
  "Crusader Chainmail" : "Body Armours",
  "Golden Caligae" : "Boots",
  "Two-Toned Boots" : "Boots",
  "Avian Slippers" : "Boots",
  "Rawhide Boots" : "Boots",
  "Goathide Boots" : "Boots",
  "Deerskin Boots" : "Boots",
  "Nubuck Boots" : "Boots",
  "Eelskin Boots" : "Boots",
  "Sharkskin Boots" : "Boots",
  "Shagreen Boots" : "Boots",
  "Stealth Boots" : "Boots",
  "Slink Boots" : "Boots",
  "Wrapped Boots" : "Boots",
  "Strapped Boots" : "Boots",
  "Clasped Boots" : "Boots",
  "Shackled Boots" : "Boots",
  "Trapper Boots" : "Boots",
  "Ambush Boots" : "Boots",
  "Carnal Boots" : "Boots",
  "Assassin's Boots" : "Boots",
  "Murder Boots" : "Boots",
  "Wool Shoes" : "Boots",
  "Velvet Slippers" : "Boots",
  "Silk Slippers" : "Boots",
  "Scholar Boots" : "Boots",
  "Satin Slippers" : "Boots",
  "Samite Slippers" : "Boots",
  "Conjurer Boots" : "Boots",
  "Arcanist Slippers" : "Boots",
  "Sorcerer Boots" : "Boots",
  "Iron Greaves" : "Boots",
  "Steel Greaves" : "Boots",
  "Plated Greaves" : "Boots",
  "Reinforced Greaves" : "Boots",
  "Antique Greaves" : "Boots",
  "Ancient Greaves" : "Boots",
  "Goliath Greaves" : "Boots",
  "Vaal Greaves" : "Boots",
  "Titan Greaves" : "Boots",
  "Leatherscale Boots" : "Boots",
  "Ironscale Boots" : "Boots",
  "Bronzescale Boots" : "Boots",
  "Steelscale Boots" : "Boots",
  "Serpentscale Boots" : "Boots",
  "Wyrmscale Boots" : "Boots",
  "Hydrascale Boots" : "Boots",
  "Dragonscale Boots" : "Boots",
  "Chain Boots" : "Boots",
  "Ringmail Boots" : "Boots",
  "Mesh Boots" : "Boots",
  "Riveted Boots" : "Boots",
  "Zealot Boots" : "Boots",
  "Soldier Boots" : "Boots",
  "Legion Boots" : "Boots",
  "Crusader Boots" : "Boots",
  "Crude Bow" : "Bows",
  "Decurve Bow" : "Bows",
  "Compound Bow" : "Bows",
  "Sniper Bow" : "Bows",
  "Ivory Bow" : "Bows",
  "Highborn Bow" : "Bows",
  "Decimation Bow" : "Bows",
  "Thicket Bow" : "Bows",
  "Citadel Bow" : "Bows",
  "Ranger Bow" : "Bows",
  "Assassin Bow" : "Bows",
  "Short Bow" : "Bows",
  "Spine Bow" : "Bows",
  "Imperial Bow" : "Bows",
  "Harbinger Bow" : "Bows",
  "Long Bow" : "Bows",
  "Composite Bow" : "Bows",
  "Recurve Bow" : "Bows",
  "Bone Bow" : "Bows",
  "Royal Bow" : "Bows",
  "Death Bow" : "Bows",
  "Grove Bow" : "Bows",
  "Reflex Bow" : "Bows",
  "Steelwood Bow" : "Bows",
  "Maraketh Bow" : "Bows",
  "Nailed Fist" : "Claws",
  "Gouger" : "Claws",
  "Tiger's Paw" : "Claws",
  "Gut Ripper" : "Claws",
  "Prehistoric Claw" : "Claws",
  "Noble Claw" : "Claws",
  "Eagle Claw" : "Claws",
  "Great White Claw" : "Claws",
  "Throat Stabber" : "Claws",
  "Hellion's Paw" : "Claws",
  "Eye Gouger" : "Claws",
  "Sharktooth Claw" : "Claws",
  "Vaal Claw" : "Claws",
  "Imperial Claw" : "Claws",
  "Terror Claw" : "Claws",
  "Awl" : "Claws",
  "Cat's Paw" : "Claws",
  "Blinder" : "Claws",
  "Timeworn Claw" : "Claws",
  "Sparkling Claw" : "Claws",
  "Fright Claw" : "Claws",
  "Thresher Claw" : "Claws",
  "Double Claw" : "Claws",
  "Twin Claw" : "Claws",
  "Gemini Claw" : "Claws",
  "Glass Shank" : "Daggers",
  "Poignard" : "Daggers",
  "Gutting Knife" : "Daggers",
  "Ambusher" : "Daggers",
  "Skinning Knife" : "Daggers",
  "Stiletto" : "Daggers",
  "Flaying Knife" : "Daggers",
  "Prong Dagger" : "Daggers",
  "Trisula" : "Daggers",
  "Sai" : "Daggers",
  "Fishing Rod" : "Fishing Rods",
  "Golden Bracers" : "Gloves",
  "Gripped Gloves" : "Gloves",
  "Fingerless Silk Gloves" : "Gloves",
  "Spiked Gloves" : "Gloves",
  "Rawhide Gloves" : "Gloves",
  "Goathide Gloves" : "Gloves",
  "Deerskin Gloves" : "Gloves",
  "Nubuck Gloves" : "Gloves",
  "Eelskin Gloves" : "Gloves",
  "Sharkskin Gloves" : "Gloves",
  "Shagreen Gloves" : "Gloves",
  "Stealth Gloves" : "Gloves",
  "Slink Gloves" : "Gloves",
  "Wrapped Mitts" : "Gloves",
  "Strapped Mitts" : "Gloves",
  "Clasped Mitts" : "Gloves",
  "Trapper Mitts" : "Gloves",
  "Ambush Mitts" : "Gloves",
  "Carnal Mitts" : "Gloves",
  "Assassin's Mitts" : "Gloves",
  "Murder Mitts" : "Gloves",
  "Wool Gloves" : "Gloves",
  "Velvet Gloves" : "Gloves",
  "Silk Gloves" : "Gloves",
  "Embroidered Gloves" : "Gloves",
  "Satin Gloves" : "Gloves",
  "Samite Gloves" : "Gloves",
  "Conjurer Gloves" : "Gloves",
  "Arcanist Gloves" : "Gloves",
  "Sorcerer Gloves" : "Gloves",
  "Iron Gauntlets" : "Gloves",
  "Plated Gauntlets" : "Gloves",
  "Bronze Gauntlets" : "Gloves",
  "Steel Gauntlets" : "Gloves",
  "Antique Gauntlets" : "Gloves",
  "Ancient Gauntlets" : "Gloves",
  "Goliath Gauntlets" : "Gloves",
  "Vaal Gauntlets" : "Gloves",
  "Titan Gauntlets" : "Gloves",
  "Fishscale Gauntlets" : "Gloves",
  "Ironscale Gauntlets" : "Gloves",
  "Bronzescale Gauntlets" : "Gloves",
  "Steelscale Gauntlets" : "Gloves",
  "Serpentscale Gauntlets" : "Gloves",
  "Wyrmscale Gauntlets" : "Gloves",
  "Hydrascale Gauntlets" : "Gloves",
  "Dragonscale Gauntlets" : "Gloves",
  "Chain Gloves" : "Gloves",
  "Ringmail Gloves" : "Gloves",
  "Mesh Gloves" : "Gloves",
  "Riveted Gloves" : "Gloves",
  "Zealot Gloves" : "Gloves",
  "Soldier Gloves" : "Gloves",
  "Legion Gloves" : "Gloves",
  "Crusader Gloves" : "Gloves",
  "Golden Visage" : "Helmets",
  "Golden Wreath" : "Helmets",
  "Bone Helmet" : "Helmets",
  "Leather Cap" : "Helmets",
  "Lion Pelt" : "Helmets",
  "Tricorne" : "Helmets",
  "Leather Hood" : "Helmets",
  "Wolf Pelt" : "Helmets",
  "Hunter Hood" : "Helmets",
  "Noble Tricorne" : "Helmets",
  "Ursine Pelt" : "Helmets",
  "Silken Hood" : "Helmets",
  "Sinner Tricorne" : "Helmets",
  "Scare Mask" : "Helmets",
  "Vaal Mask" : "Helmets",
  "Deicide Mask" : "Helmets",
  "Plague Mask" : "Helmets",
  "Iron Mask" : "Helmets",
  "Festival Mask" : "Helmets",
  "Golden Mask" : "Helmets",
  "Raven Mask" : "Helmets",
  "Callous Mask" : "Helmets",
  "Regicide Mask" : "Helmets",
  "Harlequin Mask" : "Helmets",
  "Vine Circlet" : "Helmets",
  "Mind Cage" : "Helmets",
  "Hubris Circlet" : "Helmets",
  "Iron Circlet" : "Helmets",
  "Torture Cage" : "Helmets",
  "Tribal Circlet" : "Helmets",
  "Bone Circlet" : "Helmets",
  "Lunaris Circlet" : "Helmets",
  "Steel Circlet" : "Helmets",
  "Necromancer Circlet" : "Helmets",
  "Solaris Circlet" : "Helmets",
  "Iron Hat" : "Helmets",
  "Royal Burgonet" : "Helmets",
  "Eternal Burgonet" : "Helmets",
  "Cone Helmet" : "Helmets",
  "Barbute Helmet" : "Helmets",
  "Close Helmet" : "Helmets",
  "Gladiator Helmet" : "Helmets",
  "Reaver Helmet" : "Helmets",
  "Siege Helmet" : "Helmets",
  "Samite Helmet" : "Helmets",
  "Ezomyte Burgonet" : "Helmets",
  "Battered Helm" : "Helmets",
  "Nightmare Bascinet" : "Helmets",
  "Sallet" : "Helmets",
  "Visored Sallet" : "Helmets",
  "Gilded Sallet" : "Helmets",
  "Secutor Helm" : "Helmets",
  "Fencer Helm" : "Helmets",
  "Lacquered Helmet" : "Helmets",
  "Fluted Bascinet" : "Helmets",
  "Pig-Faced Bascinet" : "Helmets",
  "Rusted Coif" : "Helmets",
  "Praetor Crown" : "Helmets",
  "Soldier Helmet" : "Helmets",
  "Great Helmet" : "Helmets",
  "Crusader Helmet" : "Helmets",
  "Aventail Helmet" : "Helmets",
  "Zealot Helmet" : "Helmets",
  "Great Crown" : "Helmets",
  "Magistrate Crown" : "Helmets",
  "Prophet Crown" : "Helmets",
  "Small Hybrid Flask" : "Hybrid Flasks",
  "Medium Hybrid Flask" : "Hybrid Flasks",
  "Large Hybrid Flask" : "Hybrid Flasks",
  "Colossal Hybrid Flask" : "Hybrid Flasks",
  "Sacred Hybrid Flask" : "Hybrid Flasks",
  "Hallowed Hybrid Flask" : "Hybrid Flasks",
  "Viridian Jewel" : "Jewel",
  "Cobalt Jewel" : "Jewel",
  "Crimson Jewel" : "Jewel",
  "Prismatic Jewel" : "Jewel",
  "Timeless Jewel" : "Jewel",
  "Small Life Flask" : "Life Flasks",
  "Sanctified Life Flask" : "Life Flasks",
  "Divine Life Flask" : "Life Flasks",
  "Eternal Life Flask" : "Life Flasks",
  "Medium Life Flask" : "Life Flasks",
  "Large Life Flask" : "Life Flasks",
  "Greater Life Flask" : "Life Flasks",
  "Grand Life Flask" : "Life Flasks",
  "Giant Life Flask" : "Life Flasks",
  "Colossal Life Flask" : "Life Flasks",
  "Sacred Life Flask" : "Life Flasks",
  "Hallowed Life Flask" : "Life Flasks",
  "Small Mana Flask" : "Mana Flasks",
  "Sanctified Mana Flask" : "Mana Flasks",
  "Divine Mana Flask" : "Mana Flasks",
  "Eternal Mana Flask" : "Mana Flasks",
  "Medium Mana Flask" : "Mana Flasks",
  "Large Mana Flask" : "Mana Flasks",
  "Greater Mana Flask" : "Mana Flasks",
  "Grand Mana Flask" : "Mana Flasks",
  "Giant Mana Flask" : "Mana Flasks",
  "Colossal Mana Flask" : "Mana Flasks",
  "Sacred Mana Flask" : "Mana Flasks",
  "Hallowed Mana Flask" : "Mana Flasks",
  "Rusted Hatchet" : "One Hand Axes",
  "Tomahawk" : "One Hand Axes",
  "Wrist Chopper" : "One Hand Axes",
  "War Axe" : "One Hand Axes",
  "Chest Splitter" : "One Hand Axes",
  "Ceremonial Axe" : "One Hand Axes",
  "Wraith Axe" : "One Hand Axes",
  "Karui Axe" : "One Hand Axes",
  "Siege Axe" : "One Hand Axes",
  "Reaver Axe" : "One Hand Axes",
  "Butcher Axe" : "One Hand Axes",
  "Jade Hatchet" : "One Hand Axes",
  "Vaal Hatchet" : "One Hand Axes",
  "Royal Axe" : "One Hand Axes",
  "Infernal Axe" : "One Hand Axes",
  "Boarding Axe" : "One Hand Axes",
  "Cleaver" : "One Hand Axes",
  "Broad Axe" : "One Hand Axes",
  "Arming Axe" : "One Hand Axes",
  "Decorative Axe" : "One Hand Axes",
  "Spectral Axe" : "One Hand Axes",
  "Jasper Axe" : "One Hand Axes",
  "Etched Hatchet" : "One Hand Axes",
  "Engraved Hatchet" : "One Hand Axes",
  "Runic Hatchet" : "One Hand Axes",
  "Driftwood Club" : "One Hand Maces",
  "Barbed Club" : "One Hand Maces",
  "Rock Breaker" : "One Hand Maces",
  "Battle Hammer" : "One Hand Maces",
  "Flanged Mace" : "One Hand Maces",
  "Ornate Mace" : "One Hand Maces",
  "Phantom Mace" : "One Hand Maces",
  "Ancestral Club" : "One Hand Maces",
  "Tenderizer" : "One Hand Maces",
  "Gavel" : "One Hand Maces",
  "Legion Hammer" : "One Hand Maces",
  "Tribal Club" : "One Hand Maces",
  "Pernarch" : "One Hand Maces",
  "Auric Mace" : "One Hand Maces",
  "Nightmare Mace" : "One Hand Maces",
  "Spiked Club" : "One Hand Maces",
  "Stone Hammer" : "One Hand Maces",
  "War Hammer" : "One Hand Maces",
  "Bladed Mace" : "One Hand Maces",
  "Ceremonial Mace" : "One Hand Maces",
  "Dream Mace" : "One Hand Maces",
  "Petrified Club" : "One Hand Maces",
  "Wyrm Mace" : "One Hand Maces",
  "Dragon Mace" : "One Hand Maces",
  "Behemoth Mace" : "One Hand Maces",
  "Charan's Sword" : "One Hand Swords",
  "Rusted Sword" : "One Hand Swords",
  "Cutlass" : "One Hand Swords",
  "Baselard" : "One Hand Swords",
  "Battle Sword" : "One Hand Swords",
  "Elder Sword" : "One Hand Swords",
  "Graceful Sword" : "One Hand Swords",
  "Twilight Blade" : "One Hand Swords",
  "Gemstone Sword" : "One Hand Swords",
  "Corsair Sword" : "One Hand Swords",
  "Gladius" : "One Hand Swords",
  "Legion Sword" : "One Hand Swords",
  "Copper Sword" : "One Hand Swords",
  "Vaal Blade" : "One Hand Swords",
  "Eternal Sword" : "One Hand Swords",
  "Midnight Blade" : "One Hand Swords",
  "Sabre" : "One Hand Swords",
  "Broad Sword" : "One Hand Swords",
  "War Sword" : "One Hand Swords",
  "Ancient Sword" : "One Hand Swords",
  "Elegant Sword" : "One Hand Swords",
  "Dusk Blade" : "One Hand Swords",
  "Variscite Blade" : "One Hand Swords",
  "Hook Sword" : "One Hand Swords",
  "Grappler" : "One Hand Swords",
  "Tiger Hook" : "One Hand Swords",
  "Cured Quiver" : "Quivers",
  "Ornate Quiver" : "Quivers",
  "Rugged Quiver" : "Quivers",
  "Conductive Quiver" : "Quivers",
  "Heavy Quiver" : "Quivers",
  "Light Quiver" : "Quivers",
  "Fire Arrow Quiver" : "Quivers",
  "Broadhead Arrow Quiver" : "Quivers",
  "Penetrating Arrow Quiver" : "Quivers",
  "Spike-Point Arrow Quiver" : "Quivers",
  "Serrated Arrow Quiver" : "Quivers",
  "Two-Point Arrow Quiver" : "Quivers",
  "Sharktooth Arrow Quiver" : "Quivers",
  "Blunt Arrow Quiver" : "Quivers",
  "Golden Hoop" : "Rings",
  "Breach Ring" : "Rings",
  "Iron Ring" : "Rings",
  "Amethyst Ring" : "Rings",
  "Diamond Ring" : "Rings",
  "Two-Stone Ring" : "Rings",
  "Unset Ring" : "Rings",
  "Coral Ring" : "Rings",
  "Paua Ring" : "Rings",
  "Gold Ring" : "Rings",
  "Topaz Ring" : "Rings",
  "Sapphire Ring" : "Rings",
  "Ruby Ring" : "Rings",
  "Prismatic Ring" : "Rings",
  "Moonstone Ring" : "Rings",
  "Steel Ring" : "Rings",
  "Opal Ring" : "Rings",
  "Vermillion Ring" : "Rings",
  "Cerulean Ring" : "Rings",
  "Butcher Knife" : "Rune Dagger",
  "Boot Blade" : "Rune Dagger",
  "Golden Kris" : "Rune Dagger",
  "Royal Skean" : "Rune Dagger",
  "Fiend Dagger" : "Rune Dagger",
  "Slaughter Knife" : "Rune Dagger",
  "Ezomyte Dagger" : "Rune Dagger",
  "Platinum Kris" : "Rune Dagger",
  "Imperial Skean" : "Rune Dagger",
  "Demon Dagger" : "Rune Dagger",
  "Carving Knife" : "Rune Dagger",
  "Boot Knife" : "Rune Dagger",
  "Copper Kris" : "Rune Dagger",
  "Skean" : "Rune Dagger",
  "Imp Dagger" : "Rune Dagger",
  "Driftwood Sceptre" : "Sceptres",
  "Sekhem" : "Sceptres",
  "Crystal Sceptre" : "Sceptres",
  "Lead Sceptre" : "Sceptres",
  "Blood Sceptre" : "Sceptres",
  "Royal Sceptre" : "Sceptres",
  "Abyssal Sceptre" : "Sceptres",
  "Karui Sceptre" : "Sceptres",
  "Tyrant's Sekhem" : "Sceptres",
  "Opal Sceptre" : "Sceptres",
  "Platinum Sceptre" : "Sceptres",
  "Darkwood Sceptre" : "Sceptres",
  "Vaal Sceptre" : "Sceptres",
  "Carnal Sceptre" : "Sceptres",
  "Void Sceptre" : "Sceptres",
  "Bronze Sceptre" : "Sceptres",
  "Quartz Sceptre" : "Sceptres",
  "Iron Sceptre" : "Sceptres",
  "Ochre Sceptre" : "Sceptres",
  "Ritual Sceptre" : "Sceptres",
  "Shadow Sceptre" : "Sceptres",
  "Grinning Fetish" : "Sceptres",
  "Horned Sceptre" : "Sceptres",
  "Stag Sceptre" : "Sceptres",
  "Sambar Sceptre" : "Sceptres",
  "Golden Flame" : "Shields",
  "Goathide Buckler" : "Shields",
  "Battle Buckler" : "Shields",
  "Golden Buckler" : "Shields",
  "Ironwood Buckler" : "Shields",
  "Lacquered Buckler" : "Shields",
  "Vaal Buckler" : "Shields",
  "Crusader Buckler" : "Shields",
  "Imperial Buckler" : "Shields",
  "Pine Buckler" : "Shields",
  "Painted Buckler" : "Shields",
  "Hammered Buckler" : "Shields",
  "War Buckler" : "Shields",
  "Gilded Buckler" : "Shields",
  "Oak Buckler" : "Shields",
  "Enameled Buckler" : "Shields",
  "Corrugated Buckler" : "Shields",
  "Spiked Bundle" : "Shields",
  "Alder Spiked Shield" : "Shields",
  "Ezomyte Spiked Shield" : "Shields",
  "Mirrored Spiked Shield" : "Shields",
  "Supreme Spiked Shield" : "Shields",
  "Driftwood Spiked Shield" : "Shields",
  "Alloyed Spiked Shield" : "Shields",
  "Burnished Spiked Shield" : "Shields",
  "Ornate Spiked Shield" : "Shields",
  "Redwood Spiked Shield" : "Shields",
  "Compound Spiked Shield" : "Shields",
  "Polished Spiked Shield" : "Shields",
  "Sovereign Spiked Shield" : "Shields",
  "Twig Spirit Shield" : "Shields",
  "Chiming Spirit Shield" : "Shields",
  "Thorium Spirit Shield" : "Shields",
  "Lacewood Spirit Shield" : "Shields",
  "Fossilised Spirit Shield" : "Shields",
  "Vaal Spirit Shield" : "Shields",
  "Harmonic Spirit Shield" : "Shields",
  "Titanium Spirit Shield" : "Shields",
  "Yew Spirit Shield" : "Shields",
  "Bone Spirit Shield" : "Shields",
  "Tarnished Spirit Shield" : "Shields",
  "Jingling Spirit Shield" : "Shields",
  "Brass Spirit Shield" : "Shields",
  "Walnut Spirit Shield" : "Shields",
  "Ivory Spirit Shield" : "Shields",
  "Ancient Spirit Shield" : "Shields",
  "Splintered Tower Shield" : "Shields",
  "Bronze Tower Shield" : "Shields",
  "Girded Tower Shield" : "Shields",
  "Crested Tower Shield" : "Shields",
  "Shagreen Tower Shield" : "Shields",
  "Ebony Tower Shield" : "Shields",
  "Ezomyte Tower Shield" : "Shields",
  "Colossal Tower Shield" : "Shields",
  "Pinnacle Tower Shield" : "Shields",
  "Corroded Tower Shield" : "Shields",
  "Rawhide Tower Shield" : "Shields",
  "Cedar Tower Shield" : "Shields",
  "Copper Tower Shield" : "Shields",
  "Reinforced Tower Shield" : "Shields",
  "Painted Tower Shield" : "Shields",
  "Buckskin Tower Shield" : "Shields",
  "Mahogany Tower Shield" : "Shields",
  "Rotted Round Shield" : "Shields",
  "Teak Round Shield" : "Shields",
  "Spiny Round Shield" : "Shields",
  "Cardinal Round Shield" : "Shields",
  "Elegant Round Shield" : "Shields",
  "Fir Round Shield" : "Shields",
  "Studded Round Shield" : "Shields",
  "Scarlet Round Shield" : "Shields",
  "Splendid Round Shield" : "Shields",
  "Maple Round Shield" : "Shields",
  "Spiked Round Shield" : "Shields",
  "Crimson Round Shield" : "Shields",
  "Baroque Round Shield" : "Shields",
  "Plank Kite Shield" : "Shields",
  "Branded Kite Shield" : "Shields",
  "Champion Kite Shield" : "Shields",
  "Mosaic Kite Shield" : "Shields",
  "Archon Kite Shield" : "Shields",
  "Linden Kite Shield" : "Shields",
  "Reinforced Kite Shield" : "Shields",
  "Layered Kite Shield" : "Shields",
  "Ceremonial Kite Shield" : "Shields",
  "Etched Kite Shield" : "Shields",
  "Steel Kite Shield" : "Shields",
  "Laminated Kite Shield" : "Shields",
  "Angelic Kite Shield" : "Shields",
  "Gnarled Branch" : "Staves",
  "Highborn Staff" : "Staves",
  "Primordial Staff" : "Staves",
  "Lathi" : "Staves",
  "Imperial Staff" : "Staves",
  "Primitive Staff" : "Staves",
  "Long Staff" : "Staves",
  "Royal Staff" : "Staves",
  "Woodful Staff" : "Staves",
  "Quarterstaff" : "Staves",
  "Crescent Staff" : "Staves",
  "Moon Staff" : "Staves",
  "Eclipse Staff" : "Staves",
  "Rusted Spike" : "One Hand Swords",
  "Burnished Foil" : "One Hand Swords",
  "Estoc" : "One Hand Swords",
  "Serrated Foil" : "One Hand Swords",
  "Primeval Rapier" : "One Hand Swords",
  "Fancy Foil" : "One Hand Swords",
  "Apex Rapier" : "One Hand Swords",
  "Dragonbone Rapier" : "One Hand Swords",
  "Tempered Foil" : "One Hand Swords",
  "Pecoraro" : "One Hand Swords",
  "Spiraled Foil" : "One Hand Swords",
  "Whalebone Rapier" : "One Hand Swords",
  "Vaal Rapier" : "One Hand Swords",
  "Jewelled Foil" : "One Hand Swords",
  "Harpy Rapier" : "One Hand Swords",
  "Battered Foil" : "One Hand Swords",
  "Basket Rapier" : "One Hand Swords",
  "Jagged Foil" : "One Hand Swords",
  "Antique Rapier" : "One Hand Swords",
  "Elegant Foil" : "One Hand Swords",
  "Thorn Rapier" : "One Hand Swords",
  "Wyrmbone Rapier" : "One Hand Swords",
  "Smallsword" : "One Hand Swords",
  "Courtesan Sword" : "One Hand Swords",
  "Dragoon Sword" : "One Hand Swords",
  "Stone Axe" : "Two Hand Axes",
  "Headsman Axe" : "Two Hand Axes",
  "Labrys" : "Two Hand Axes",
  "Noble Axe" : "Two Hand Axes",
  "Abyssal Axe" : "Two Hand Axes",
  "Karui Chopper" : "Two Hand Axes",
  "Sundering Axe" : "Two Hand Axes",
  "Ezomyte Axe" : "Two Hand Axes",
  "Vaal Axe" : "Two Hand Axes",
  "Despot Axe" : "Two Hand Axes",
  "Void Axe" : "Two Hand Axes",
  "Jade Chopper" : "Two Hand Axes",
  "Woodsplitter" : "Two Hand Axes",
  "Poleaxe" : "Two Hand Axes",
  "Double Axe" : "Two Hand Axes",
  "Gilded Axe" : "Two Hand Axes",
  "Shadow Axe" : "Two Hand Axes",
  "Jasper Chopper" : "Two Hand Axes",
  "Timber Axe" : "Two Hand Axes",
  "Dagger Axe" : "Two Hand Axes",
  "Talon Axe" : "Two Hand Axes",
  "Fleshripper" : "Two Hand Axes",
  "Driftwood Maul" : "Two Hand Maces",
  "Steelhead" : "Two Hand Maces",
  "Spiny Maul" : "Two Hand Maces",
  "Plated Maul" : "Two Hand Maces",
  "Dread Maul" : "Two Hand Maces",
  "Karui Maul" : "Two Hand Maces",
  "Colossus Mallet" : "Two Hand Maces",
  "Piledriver" : "Two Hand Maces",
  "Meatgrinder" : "Two Hand Maces",
  "Imperial Maul" : "Two Hand Maces",
  "Terror Maul" : "Two Hand Maces",
  "Tribal Maul" : "Two Hand Maces",
  "Mallet" : "Two Hand Maces",
  "Sledgehammer" : "Two Hand Maces",
  "Jagged Maul" : "Two Hand Maces",
  "Brass Maul" : "Two Hand Maces",
  "Fright Maul" : "Two Hand Maces",
  "Totemic Maul" : "Two Hand Maces",
  "Great Mallet" : "Two Hand Maces",
  "Morning Star" : "Two Hand Maces",
  "Solar Maul" : "Two Hand Maces",
  "Coronal Maul" : "Two Hand Maces",
  "Corroded Blade" : "Two Hand Swords",
  "Highland Blade" : "Two Hand Swords",
  "Engraved Greatsword" : "Two Hand Swords",
  "Tiger Sword" : "Two Hand Swords",
  "Wraith Sword" : "Two Hand Swords",
  "Headman's Sword" : "Two Hand Swords",
  "Reaver Sword" : "Two Hand Swords",
  "Ezomyte Blade" : "Two Hand Swords",
  "Vaal Greatsword" : "Two Hand Swords",
  "Lion Sword" : "Two Hand Swords",
  "Infernal Sword" : "Two Hand Swords",
  "Longsword" : "Two Hand Swords",
  "Bastard Sword" : "Two Hand Swords",
  "Two-Handed Sword" : "Two Hand Swords",
  "Etched Greatsword" : "Two Hand Swords",
  "Ornate Sword" : "Two Hand Swords",
  "Spectral Sword" : "Two Hand Swords",
  "Butcher Sword" : "Two Hand Swords",
  "Footman Sword" : "Two Hand Swords",
  "Curved Blade" : "Two Hand Swords",
  "Lithe Blade" : "Two Hand Swords",
  "Exquisite Blade" : "Two Hand Swords",
  "Basalt Flask" : "Utility Flasks",
  "Aquamarine Flask" : "Utility Flasks",
  "Stibnite Flask" : "Utility Flasks",
  "Sulphur Flask" : "Utility Flasks",
  "Silver Flask" : "Utility Flasks",
  "Bismuth Flask" : "Utility Flasks",
  "Ruby Flask" : "Utility Flasks",
  "Sapphire Flask" : "Utility Flasks",
  "Topaz Flask" : "Utility Flasks",
  "Granite Flask" : "Utility Flasks",
  "Quicksilver Flask" : "Utility Flasks",
  "Amethyst Flask" : "Utility Flasks",
  "Quartz Flask" : "Utility Flasks",
  "Jade Flask" : "Utility Flasks",
  "Diamond Flask" : "Critical Utility Flasks",
  "Driftwood Wand" : "Wands",
  "Serpent Wand" : "Wands",
  "Omen Wand" : "Wands",
  "Demon's Horn" : "Wands",
  "Imbued Wand" : "Wands",
  "Opal Wand" : "Wands",
  "Tornado Wand" : "Wands",
  "Prophecy Wand" : "Wands",
  "Goat's Horn" : "Wands",
  "Carved Wand" : "Wands",
  "Quartz Wand" : "Wands",
  "Spiraled Wand" : "Wands",
  "Sage Wand" : "Wands",
  "Faun's Horn" : "Wands",
  "Engraved Wand" : "Wands",
  "Crystal Wand" : "Wands",
  "Convoking Wand" : "Wands",
  "Pagan Wand" : "Wands",
  "Heathen Wand" : "Wands",
  "Profane Wand" : "Wands",
  "Military Staff" : "Warstaff",
  "Serpentine Staff" : "Warstaff",
  "Foul Staff" : "Warstaff",
  "Ezomyte Staff" : "Warstaff",
  "Maelström Staff" : "Warstaff",
  "Judgement Staff" : "Warstaff",
  "Iron Staff" : "Warstaff",
  "Coiled Staff" : "Warstaff",
  "Vile Staff" : "Warstaff"
};

const gemBaseTypes = {
  "Abyssal Cry" : "Active Skill Gems",
  "Ancestral Warchief" : "Active Skill Gems",
  "Anger" : "Active Skill Gems",
  "Animate Guardian" : "Active Skill Gems",
  "Animate Weapon" : "Active Skill Gems",
  "Arc" : "Active Skill Gems",
  "Arctic Armour" : "Active Skill Gems",
  "Arctic Breath" : "Active Skill Gems",
  "Armageddon Brand" : "Active Skill Gems",
  "Ball Lightning" : "Active Skill Gems",
  "Barrage" : "Active Skill Gems",
  "Bear Trap" : "Active Skill Gems",
  "Berserk" : "Active Skill Gems",
  "Blade Vortex" : "Active Skill Gems",
  "Bladefall" : "Active Skill Gems",
  "Bladestorm" : "Active Skill Gems",
  "Blast Rain" : "Active Skill Gems",
  "Blight" : "Active Skill Gems",
  "Blink Arrow" : "Active Skill Gems",
  "Blood and Sand" : "Active Skill Gems",
  "Blood Rage" : "Active Skill Gems",
  "Unearth" : "Active Skill Gems",
  "Bone Offering" : "Active Skill Gems",
  "Burning Arrow" : "Active Skill Gems",
  "Chain Hook" : "Active Skill Gems",
  "Blade Flurry" : "Active Skill Gems",
  "Charged Dash" : "Active Skill Gems",
  "Clarity" : "Active Skill Gems",
  "Cleave" : "Active Skill Gems",
  "Cobra Lash" : "Active Skill Gems",
  "Purity of Ice" : "Active Skill Gems",
  "Cold Snap" : "Active Skill Gems",
  "Conductivity" : "Active Skill Gems",
  "Consecrated Path" : "Active Skill Gems",
  "Contagion" : "Active Skill Gems",
  "Conversion Trap" : "Active Skill Gems",
  "Convocation" : "Active Skill Gems",
  "Cremation" : "Active Skill Gems",
  "Bodyswap" : "Active Skill Gems",
  "Assassin's Mark" : "Active Skill Gems",
  "Cyclone" : "Active Skill Gems",
  "Malevolence" : "Active Skill Gems",
  "Dark Pact" : "Active Skill Gems",
  "Bane" : "Active Skill Gems",
  "Dash" : "Active Skill Gems",
  "Decoy Totem" : "Active Skill Gems",
  "Desecrate" : "Active Skill Gems",
  "Determination" : "Active Skill Gems",
  "Detonate Dead" : "Active Skill Gems",
  "Detonate Mines" : "Active Skill Gems",
  "Devouring Totem" : "Active Skill Gems",
  "Discharge" : "Active Skill Gems",
  "Discipline" : "Active Skill Gems",
  "Divine Ire" : "Active Skill Gems",
  "Dominating Blow" : "Active Skill Gems",
  "Double Strike" : "Active Skill Gems",
  "Dread Banner" : "Active Skill Gems",
  "Dual Strike" : "Active Skill Gems",
  "Earthquake" : "Active Skill Gems",
  "Elemental Hit" : "Active Skill Gems",
  "Elemental Weakness" : "Active Skill Gems",
  "Enduring Cry" : "Active Skill Gems",
  "Enfeeble" : "Active Skill Gems",
  "Essence Drain" : "Active Skill Gems",
  "Ethereal Knives" : "Active Skill Gems",
  "Explosive Arrow" : "Active Skill Gems",
  "Scorching Ray" : "Active Skill Gems",
  "Pyroclast Mine" : "Active Skill Gems",
  "Purity of Fire" : "Active Skill Gems",
  "Fire Trap" : "Active Skill Gems",
  "Fireball" : "Active Skill Gems",
  "Firestorm" : "Active Skill Gems",
  "Flame Dash" : "Active Skill Gems",
  "Holy Flame Totem" : "Active Skill Gems",
  "Flame Surge" : "Active Skill Gems",
  "Flameblast" : "Active Skill Gems",
  "Flamethrower Trap" : "Active Skill Gems",
  "Flammability" : "Active Skill Gems",
  "Flesh and Stone" : "Active Skill Gems",
  "Flesh Offering" : "Active Skill Gems",
  "Flicker Strike" : "Active Skill Gems",
  "Icicle Mine" : "Active Skill Gems",
  "Freezing Pulse" : "Active Skill Gems",
  "Frenzy" : "Active Skill Gems",
  "Frost Blades" : "Active Skill Gems",
  "Frostbolt" : "Active Skill Gems",
  "Vortex" : "Active Skill Gems",
  "Frost Bomb" : "Active Skill Gems",
  "Frost Wall" : "Active Skill Gems",
  "Frostbite" : "Active Skill Gems",
  "Frostblink" : "Active Skill Gems",
  "Glacial Cascade" : "Active Skill Gems",
  "Glacial Hammer" : "Active Skill Gems",
  "Grace" : "Active Skill Gems",
  "Ground Slam" : "Active Skill Gems",
  "Haste" : "Active Skill Gems",
  "Hatred" : "Active Skill Gems",
  "Heavy Strike" : "Active Skill Gems",
  "Herald of Agony" : "Active Skill Gems",
  "Herald of Ash" : "Active Skill Gems",
  "Herald of Ice" : "Active Skill Gems",
  "Herald of Purity" : "Active Skill Gems",
  "Herald of Thunder" : "Active Skill Gems",
  "Ice Crash" : "Active Skill Gems",
  "Ice Nova" : "Active Skill Gems",
  "Ice Shot" : "Active Skill Gems",
  "Siphoning Trap" : "Active Skill Gems",
  "Ice Spear" : "Active Skill Gems",
  "Ice Trap" : "Active Skill Gems",
  "Immortal Call" : "Active Skill Gems",
  "Incinerate" : "Active Skill Gems",
  "Infernal Blow" : "Active Skill Gems",
  "Kinetic Blast" : "Active Skill Gems",
  "Lacerate" : "Active Skill Gems",
  "Lancing Steel" : "Active Skill Gems",
  "Leap Slam" : "Active Skill Gems",
  "Lightning Arrow" : "Active Skill Gems",
  "Purity of Lightning" : "Active Skill Gems",
  "Lightning Strike" : "Active Skill Gems",
  "Lightning Tendrils" : "Active Skill Gems",
  "Lightning Spire Trap" : "Active Skill Gems",
  "Lightning Trap" : "Active Skill Gems",
  "Lightning Warp" : "Active Skill Gems",
  "Magma Orb" : "Active Skill Gems",
  "Ancestral Protector" : "Active Skill Gems",
  "Mirror Arrow" : "Active Skill Gems",
  "Molten Shell" : "Active Skill Gems",
  "Molten Strike" : "Active Skill Gems",
  "Phase Run" : "Active Skill Gems",
  "Vulnerability" : "Active Skill Gems",
  "Orb of Storms" : "Active Skill Gems",
  "Perforate" : "Active Skill Gems",
  "Pestilent Strike" : "Active Skill Gems",
  "Seismic Trap" : "Active Skill Gems",
  "Plague Bearer" : "Active Skill Gems",
  "Poacher's Mark" : "Active Skill Gems",
  "Caustic Arrow" : "Active Skill Gems",
  "Portal" : "Active Skill Gems",
  "Power Siphon" : "Active Skill Gems",
  "Precision" : "Active Skill Gems",
  "Pride" : "Active Skill Gems",
  "Projectile Weakness" : "Active Skill Gems",
  "Puncture" : "Active Skill Gems",
  "Punishment" : "Active Skill Gems",
  "Wave of Conviction" : "Active Skill Gems",
  "Purity of Elements" : "Active Skill Gems",
  "Rain of Arrows" : "Active Skill Gems",
  "Raise Spectre" : "Active Skill Gems",
  "Raise Zombie" : "Active Skill Gems",
  "Rallying Cry" : "Active Skill Gems",
  "Reave" : "Active Skill Gems",
  "Brand Recall" : "Active Skill Gems",
  "Reckoning" : "Active Skill Gems",
  "Rejuvenation Totem" : "Active Skill Gems",
  "Righteous Fire" : "Active Skill Gems",
  "Riposte" : "Active Skill Gems",
  "Purifying Flame" : "Active Skill Gems",
  "Scourge Arrow" : "Active Skill Gems",
  "Searing Bond" : "Active Skill Gems",
  "Shattering Steel" : "Active Skill Gems",
  "Shield Charge" : "Active Skill Gems",
  "Shock Nova" : "Active Skill Gems",
  "Shockwave Totem" : "Active Skill Gems",
  "Shrapnel Shot" : "Active Skill Gems",
  "Explosive Trap" : "Active Skill Gems",
  "Siege Ballista" : "Active Skill Gems",
  "Smite" : "Active Skill Gems",
  "Smoke Mine" : "Active Skill Gems",
  "Soulrend" : "Active Skill Gems",
  "Spark" : "Active Skill Gems",
  "Zealotry" : "Active Skill Gems",
  "Spirit Offering" : "Active Skill Gems",
  "Split Arrow" : "Active Skill Gems",
  "Static Strike" : "Active Skill Gems",
  "Steelskin" : "Active Skill Gems",
  "Storm Brand" : "Active Skill Gems",
  "Storm Burst" : "Active Skill Gems",
  "Storm Call" : "Active Skill Gems",
  "Stormblast Mine" : "Active Skill Gems",
  "Summon Carrion Golem" : "Active Skill Gems",
  "Summon Chaos Golem" : "Active Skill Gems",
  "Summon Flame Golem" : "Active Skill Gems",
  "Summon Ice Golem" : "Active Skill Gems",
  "Summon Lightning Golem" : "Active Skill Gems",
  "Summon Raging Spirit" : "Active Skill Gems",
  "Summon Holy Relic" : "Active Skill Gems",
  "Summon Stone Golem" : "Active Skill Gems",
  "Summon Skeletons" : "Active Skill Gems",
  "Summon Skitterbots" : "Active Skill Gems",
  "Sunder" : "Active Skill Gems",
  "Sweep" : "Active Skill Gems",
  "Tectonic Slam" : "Active Skill Gems",
  "Tempest Shield" : "Active Skill Gems",
  "Temporal Chains" : "Active Skill Gems",
  "Spectral Shield Throw" : "Active Skill Gems",
  "Spectral Throw" : "Active Skill Gems",
  "Tornado Shot" : "Active Skill Gems",
  "Toxic Rain" : "Active Skill Gems",
  "Vaal Ancestral Warchief" : "Active Skill Gems",
  "Vaal Arc" : "Active Skill Gems",
  "Vaal Blade Vortex" : "Active Skill Gems",
  "Vaal Blight" : "Active Skill Gems",
  "Vaal Burning Arrow" : "Active Skill Gems",
  "Vaal Clarity" : "Active Skill Gems",
  "Vaal Impurity of Ice" : "Active Skill Gems",
  "Vaal Cold Snap" : "Active Skill Gems",
  "Vaal Cyclone" : "Active Skill Gems",
  "Vaal Detonate Dead" : "Active Skill Gems",
  "Vaal Discipline" : "Active Skill Gems",
  "Vaal Double Strike" : "Active Skill Gems",
  "Vaal Earthquake" : "Active Skill Gems",
  "Vaal Impurity of Fire" : "Active Skill Gems",
  "Vaal Fireball" : "Active Skill Gems",
  "Vaal Flameblast" : "Active Skill Gems",
  "Vaal Glacial Hammer" : "Active Skill Gems",
  "Vaal Grace" : "Active Skill Gems",
  "Vaal Ground Slam" : "Active Skill Gems",
  "Vaal Haste" : "Active Skill Gems",
  "Vaal Ice Nova" : "Active Skill Gems",
  "Vaal Immortal Call" : "Active Skill Gems",
  "Vaal Impurity of Lightning" : "Active Skill Gems",
  "Vaal Lightning Strike" : "Active Skill Gems",
  "Vaal Lightning Trap" : "Active Skill Gems",
  "Vaal Lightning Warp" : "Active Skill Gems",
  "Vaal Molten Shell" : "Active Skill Gems",
  "Vaal Breach" : "Active Skill Gems",
  "Vaal Power Siphon" : "Active Skill Gems",
  "Vaal Rain of Arrows" : "Active Skill Gems",
  "Vaal Reave" : "Active Skill Gems",
  "Vaal Righteous Fire" : "Active Skill Gems",
  "Vaal Spark" : "Active Skill Gems",
  "Vaal Storm Call" : "Active Skill Gems",
  "Vaal Summon Skeletons" : "Active Skill Gems",
  "Vaal Spectral Throw" : "Active Skill Gems",
  "Vengeance" : "Active Skill Gems",
  "Venom Gyre" : "Active Skill Gems",
  "Vigilant Strike" : "Active Skill Gems",
  "Viper Strike" : "Active Skill Gems",
  "Vitality" : "Active Skill Gems",
  "Volatile Dead" : "Active Skill Gems",
  "Despair" : "Active Skill Gems",
  "War Banner" : "Active Skill Gems",
  "Warlord's Mark" : "Active Skill Gems",
  "Whirling Blades" : "Active Skill Gems",
  "Wild Strike" : "Active Skill Gems",
  "Winter Orb" : "Active Skill Gems",
  "Wither" : "Active Skill Gems",
  "Withering Step" : "Active Skill Gems",
  "Wrath" : "Active Skill Gems",
  "Added Chaos Damage Support" : "Support Skill Gems",
  "Added Cold Damage Support" : "Support Skill Gems",
  "Added Fire Damage Support" : "Support Skill Gems",
  "Added Lightning Damage Support" : "Support Skill Gems",
  "Additional Accuracy Support" : "Support Skill Gems",
  "Empower Support" : "Support Skill Gems",
  "Enhance Support" : "Support Skill Gems",
  "Enlighten Support" : "Support Skill Gems",
  "Arcane Surge Support" : "Support Skill Gems",
  "Blasphemy Support" : "Support Skill Gems",
  "Blind Support" : "Support Skill Gems",
  "Block Chance Reduction Support" : "Support Skill Gems",
  "Blood Magic Support" : "Support Skill Gems",
  "Bloodlust Support" : "Support Skill Gems",
  "Bonechill Support" : "Support Skill Gems",
  "Brutality Support" : "Support Skill Gems",
  "Cast On Critical Strike Support" : "Support Skill Gems",
  "Cast when Damage Taken Support" : "Support Skill Gems",
  "Cast on Death Support" : "Support Skill Gems",
  "Cast on Melee Kill Support" : "Support Skill Gems",
  "Cast when Stunned Support" : "Support Skill Gems",
  "Cast while Channelling Support" : "Support Skill Gems",
  "Chain Support" : "Support Skill Gems",
  "Chance to Bleed Support" : "Support Skill Gems",
  "Chance to Flee Support" : "Support Skill Gems",
  "Combustion Support" : "Support Skill Gems",
  "Withering Touch Support" : "Support Skill Gems",
  "Charged Mines Support" : "Support Skill Gems",
  "Close Combat Support" : "Support Skill Gems",
  "Cluster Traps Support" : "Support Skill Gems",
  "Cold Penetration Support" : "Support Skill Gems",
  "Cold to Fire Support" : "Support Skill Gems",
  "Concentrated Effect Support" : "Support Skill Gems",
  "Controlled Destruction Support" : "Support Skill Gems",
  "Culling Strike Support" : "Support Skill Gems",
  "Curse On Hit Support" : "Support Skill Gems",
  "Hypothermia Support" : "Support Skill Gems",
  "Deadly Ailments Support" : "Support Skill Gems",
  "Deathmark Support" : "Support Skill Gems",
  "Decay Support" : "Support Skill Gems",
  "Efficacy Support" : "Support Skill Gems",
  "Elemental Focus Support" : "Support Skill Gems",
  "Elemental Proliferation Support" : "Support Skill Gems",
  "Endurance Charge on Melee Stun Support" : "Support Skill Gems",
  "Energy Leech Support" : "Support Skill Gems",
  "Faster Attacks Support" : "Support Skill Gems",
  "Faster Casting Support" : "Support Skill Gems",
  "Faster Projectiles Support" : "Support Skill Gems",
  "Feeding Frenzy Support" : "Support Skill Gems",
  "Fire Penetration Support" : "Support Skill Gems",
  "Fork Support" : "Support Skill Gems",
  "Fortify Support" : "Support Skill Gems",
  "Ice Bite Support" : "Support Skill Gems",
  "Charged Traps Support" : "Support Skill Gems",
  "Generosity Support" : "Support Skill Gems",
  "Greater Multiple Projectiles Support" : "Support Skill Gems",
  "Unleash Support" : "Support Skill Gems",
  "Intensify Support" : "Support Skill Gems",
  "High-Impact Mine Support" : "Support Skill Gems",
  "Ignite Proliferation Support" : "Support Skill Gems",
  "Immolate Support" : "Support Skill Gems",
  "Impale Support" : "Support Skill Gems",
  "Increased Area of Effect Support" : "Support Skill Gems",
  "Burning Damage Support" : "Support Skill Gems",
  "Increased Critical Damage Support" : "Support Skill Gems",
  "Increased Critical Strikes Support" : "Support Skill Gems",
  "Increased Duration Support" : "Support Skill Gems",
  "Infernal Legion Support" : "Support Skill Gems",
  "Iron Grip Support" : "Support Skill Gems",
  "Iron Will Support" : "Support Skill Gems",
  "Item Quantity Support" : "Support Skill Gems",
  "Item Rarity Support" : "Support Skill Gems",
  "Knockback Support" : "Support Skill Gems",
  "Lesser Multiple Projectiles Support" : "Support Skill Gems",
  "Lesser Poison Support" : "Support Skill Gems",
  "Life Gain on Hit Support" : "Support Skill Gems",
  "Life Leech Support" : "Support Skill Gems",
  "Lightning Penetration Support" : "Support Skill Gems",
  "Maim Support" : "Support Skill Gems",
  "Mana Leech Support" : "Support Skill Gems",
  "Meat Shield Support" : "Support Skill Gems",
  "Damage on Full Life Support" : "Support Skill Gems",
  "Melee Physical Damage Support" : "Support Skill Gems",
  "Melee Splash Support" : "Support Skill Gems",
  "Minefield Support" : "Support Skill Gems",
  "Minion Damage Support" : "Support Skill Gems",
  "Minion Life Support" : "Support Skill Gems",
  "Minion Speed Support" : "Support Skill Gems",
  "Mirage Archer Support" : "Support Skill Gems",
  "Multiple Totems Support" : "Support Skill Gems",
  "Multiple Traps Support" : "Support Skill Gems",
  "Spell Echo Support" : "Support Skill Gems",
  "Multistrike Support" : "Support Skill Gems",
  "Nightblade Support" : "Support Skill Gems",
  "Onslaught Support" : "Support Skill Gems",
  "Innervate Support" : "Support Skill Gems",
  "Volley Support" : "Support Skill Gems",
  "Vicious Projectiles Support" : "Support Skill Gems",
  "Physical to Lightning Support" : "Support Skill Gems",
  "Pierce Support" : "Support Skill Gems",
  "Point Blank Support" : "Support Skill Gems",
  "Poison Support" : "Support Skill Gems",
  "Power Charge On Critical Support" : "Support Skill Gems",
  "Pulverise Support" : "Support Skill Gems",
  "Rage Support" : "Support Skill Gems",
  "Ranged Attack Totem Support" : "Support Skill Gems",
  "Swift Affliction Support" : "Support Skill Gems",
  "Less Duration Support" : "Support Skill Gems",
  "Inspiration Support" : "Support Skill Gems",
  "Blastchain Mine Support" : "Support Skill Gems",
  "Ruthless Support" : "Support Skill Gems",
  "Shockwave Support" : "Support Skill Gems",
  "Slower Projectiles Support" : "Support Skill Gems",
  "Spell Cascade Support" : "Support Skill Gems",
  "Spell Totem Support" : "Support Skill Gems",
  "Ancestral Call Support" : "Support Skill Gems",
  "Infused Channelling Support" : "Support Skill Gems",
  "Stun Support" : "Support Skill Gems",
  "Elemental Army Support" : "Support Skill Gems",
  "Summon Phantasm Support" : "Support Skill Gems",
  "Swift Assembly Support" : "Support Skill Gems",
  "Trap Support" : "Support Skill Gems",
  "Trap and Mine Damage Support" : "Support Skill Gems",
  "Advanced Traps Support" : "Support Skill Gems",
  "Unbound Ailments Support" : "Support Skill Gems",
  "Vile Toxins Support" : "Support Skill Gems",
  "Void Manipulation Support" : "Support Skill Gems",
  "Elemental Damage with Attacks Support" : "Support Skill Gems"
};

const otherBaseTypes = {
  "Simple Rope Net" : "Currency",
  "Thaumaturgical Net" : "Currency",
  "Necromancy Net" : "Currency",
  "Reinforced Rope Net" : "Currency",
  "Strong Rope Net" : "Currency",
  "Simple Iron Net" : "Currency",
  "Reinforced Iron Net" : "Currency",
  "Strong Iron Net" : "Currency",
  "Simple Steel Net" : "Currency",
  "Reinforced Steel Net" : "Currency",
  "Strong Steel Net" : "Currency",
  "Apprentice Cartographer's Sextant" : "Currency",
  "Master Cartographer's Sextant" : "Currency",
  "Journeyman Cartographer's Sextant" : "Currency",
  "Orb of Augmentation" : "Currency",
  "Exalted Orb" : "Currency",
  "Exalted Shard" : "Currency",
  "Armourer's Scrap" : "Currency",
  "Splinter of Chayula" : "Currency",
  "Splinter of Tul" : "Currency",
  "Splinter of Xoph" : "Currency",
  "Splinter of Esh" : "Currency",
  "Splinter of Uul-Netol" : "Currency",
  "Blessing of Chayula" : "Currency",
  "Blessing of Tul" : "Currency",
  "Blessing of Xoph" : "Currency",
  "Blessing of Esh" : "Currency",
  "Blessing of Uul-Netol" : "Currency",
  "Orb of Scouring" : "Currency",
  "Vaal Orb" : "Currency",
  "Remnant of Corruption" : "Currency",
  "Hollow Fossil" : "Currency",
  "Serrated Fossil" : "Currency",
  "Corroded Fossil" : "Currency",
  "Aetheric Fossil" : "Currency",
  "Aberrant Fossil" : "Currency",
  "Frigid Fossil" : "Currency",
  "Glyphic Fossil" : "Currency",
  "Dense Fossil" : "Currency",
  "Prismatic Fossil" : "Currency",
  "Enchanted Fossil" : "Currency",
  "Scorched Fossil" : "Currency",
  "Faceted Fossil" : "Currency",
  "Pristine Fossil" : "Currency",
  "Metallic Fossil" : "Currency",
  "Sanctified Fossil" : "Currency",
  "Lucent Fossil" : "Currency",
  "Bound Fossil" : "Currency",
  "Fractured Fossil" : "Currency",
  "Jagged Fossil" : "Currency",
  "Perfect Fossil" : "Currency",
  "Tangled Fossil" : "Currency",
  "Gilded Fossil" : "Currency",
  "Encrusted Fossil" : "Currency",
  "Shuddering Fossil" : "Currency",
  "Bloodstained Fossil" : "Currency",
  "Mirror of Kalandra" : "Currency",
  "Mirror Shard" : "Currency",
  "Muttering Essence of Anger" : "Currency",
  "Weeping Essence of Anger" : "Currency",
  "Wailing Essence of Anger" : "Currency",
  "Screaming Essence of Anger" : "Currency",
  "Shrieking Essence of Anger" : "Currency",
  "Deafening Essence of Anger" : "Currency",
  "Wailing Essence of Anguish" : "Currency",
  "Screaming Essence of Anguish" : "Currency",
  "Shrieking Essence of Anguish" : "Currency",
  "Deafening Essence of Anguish" : "Currency",
  "Whispering Essence of Contempt" : "Currency",
  "Muttering Essence of Contempt" : "Currency",
  "Weeping Essence of Contempt" : "Currency",
  "Wailing Essence of Contempt" : "Currency",
  "Screaming Essence of Contempt" : "Currency",
  "Shrieking Essence of Contempt" : "Currency",
  "Deafening Essence of Contempt" : "Currency",
  "Essence of Delirium" : "Currency",
  "Weeping Essence of Doubt" : "Currency",
  "Wailing Essence of Doubt" : "Currency",
  "Screaming Essence of Doubt" : "Currency",
  "Shrieking Essence of Doubt" : "Currency",
  "Deafening Essence of Doubt" : "Currency",
  "Screaming Essence of Dread" : "Currency",
  "Shrieking Essence of Dread" : "Currency",
  "Deafening Essence of Dread" : "Currency",
  "Screaming Essence of Envy" : "Currency",
  "Shrieking Essence of Envy" : "Currency",
  "Deafening Essence of Envy" : "Currency",
  "Muttering Essence of Fear" : "Currency",
  "Weeping Essence of Fear" : "Currency",
  "Wailing Essence of Fear" : "Currency",
  "Screaming Essence of Fear" : "Currency",
  "Shrieking Essence of Fear" : "Currency",
  "Deafening Essence of Fear" : "Currency",
  "Whispering Essence of Greed" : "Currency",
  "Muttering Essence of Greed" : "Currency",
  "Weeping Essence of Greed" : "Currency",
  "Wailing Essence of Greed" : "Currency",
  "Screaming Essence of Greed" : "Currency",
  "Shrieking Essence of Greed" : "Currency",
  "Deafening Essence of Greed" : "Currency",
  "Whispering Essence of Hatred" : "Currency",
  "Muttering Essence of Hatred" : "Currency",
  "Weeping Essence of Hatred" : "Currency",
  "Wailing Essence of Hatred" : "Currency",
  "Screaming Essence of Hatred" : "Currency",
  "Shrieking Essence of Hatred" : "Currency",
  "Deafening Essence of Hatred" : "Currency",
  "Essence of Horror" : "Currency",
  "Essence of Hysteria" : "Currency",
  "Essence of Insanity" : "Currency",
  "Wailing Essence of Loathing" : "Currency",
  "Screaming Essence of Loathing" : "Currency",
  "Shrieking Essence of Loathing" : "Currency",
  "Deafening Essence of Loathing" : "Currency",
  "Screaming Essence of Misery" : "Currency",
  "Shrieking Essence of Misery" : "Currency",
  "Deafening Essence of Misery" : "Currency",
  "Weeping Essence of Rage" : "Currency",
  "Wailing Essence of Rage" : "Currency",
  "Screaming Essence of Rage" : "Currency",
  "Shrieking Essence of Rage" : "Currency",
  "Deafening Essence of Rage" : "Currency",
  "Screaming Essence of Scorn" : "Currency",
  "Shrieking Essence of Scorn" : "Currency",
  "Deafening Essence of Scorn" : "Currency",
  "Muttering Essence of Sorrow" : "Currency",
  "Weeping Essence of Sorrow" : "Currency",
  "Wailing Essence of Sorrow" : "Currency",
  "Screaming Essence of Sorrow" : "Currency",
  "Shrieking Essence of Sorrow" : "Currency",
  "Deafening Essence of Sorrow" : "Currency",
  "Wailing Essence of Spite" : "Currency",
  "Screaming Essence of Spite" : "Currency",
  "Shrieking Essence of Spite" : "Currency",
  "Deafening Essence of Spite" : "Currency",
  "Weeping Essence of Suffering" : "Currency",
  "Wailing Essence of Suffering" : "Currency",
  "Screaming Essence of Suffering" : "Currency",
  "Shrieking Essence of Suffering" : "Currency",
  "Deafening Essence of Suffering" : "Currency",
  "Muttering Essence of Torment" : "Currency",
  "Weeping Essence of Torment" : "Currency",
  "Wailing Essence of Torment" : "Currency",
  "Screaming Essence of Torment" : "Currency",
  "Shrieking Essence of Torment" : "Currency",
  "Deafening Essence of Torment" : "Currency",
  "Whispering Essence of Woe" : "Currency",
  "Muttering Essence of Woe" : "Currency",
  "Weeping Essence of Woe" : "Currency",
  "Wailing Essence of Woe" : "Currency",
  "Screaming Essence of Woe" : "Currency",
  "Shrieking Essence of Woe" : "Currency",
  "Deafening Essence of Woe" : "Currency",
  "Weeping Essence of Wrath" : "Currency",
  "Wailing Essence of Wrath" : "Currency",
  "Screaming Essence of Wrath" : "Currency",
  "Shrieking Essence of Wrath" : "Currency",
  "Deafening Essence of Wrath" : "Currency",
  "Wailing Essence of Zeal" : "Currency",
  "Screaming Essence of Zeal" : "Currency",
  "Shrieking Essence of Zeal" : "Currency",
  "Deafening Essence of Zeal" : "Currency",
  "Glassblower's Bauble" : "Currency",
  "Gemcutter's Prism" : "Currency",
  "Scroll of Wisdom" : "Currency",
  "Scroll Fragment" : "Currency",
  "Vial of Sacrifice" : "Currency",
  "Vial of the Ghost" : "Currency",
  "Vial of Transcendence" : "Currency",
  "Vial of Fate" : "Currency",
  "Vial of Summoning" : "Currency",
  "Vial of the Ritual" : "Currency",
  "Vial of Consequence" : "Currency",
  "Vial of Awakening" : "Currency",
  "Vial of Dominance" : "Currency",
  "Bestiary Orb" : "Currency",
  "Imprinted Bestiary Orb" : "Currency",
  "Timeless Eternal Empire Splinter" : "Currency",
  "Timeless Karui Splinter" : "Currency",
  "Timeless Maraketh Splinter" : "Currency",
  "Timeless Templar Splinter" : "Currency",
  "Timeless Vaal Splinter" : "Currency",
  "Cartographer's Chisel" : "Currency",
  "Divine Orb" : "Currency",
  "Orb of Regret" : "Currency",
  "Perandus Coin" : "Currency",
  "Portal Scroll" : "Currency",
  "Orb of Annulment" : "Currency",
  "Annulment Shard" : "Currency",
  "Blessed Orb" : "Currency",
  "Orb of Alteration" : "Currency",
  "Alteration Shard" : "Currency",
  "Orb of Horizons" : "Currency",
  "Horizon Shard" : "Currency",
  "Chaos Orb" : "Currency",
  "Chaos Shard" : "Currency",
  "Chromatic Orb" : "Currency",
  "Orb of Fusing" : "Currency",
  "Jeweller's Orb" : "Currency",
  "Ancient Orb" : "Currency",
  "Ancient Shard" : "Currency",
  "Unshaping Orb" : "Currency",
  "Albino Rhoa Feather" : "Currency",
  "Master Cartographer's Seal" : "Currency",
  "Apprentice Cartographer's Seal" : "Currency",
  "Journeyman Cartographer's Seal" : "Currency",
  "Silver Coin" : "Currency",
  "Engineer's Orb" : "Currency",
  "Engineer's Shard" : "Currency",
  "Regal Orb" : "Currency",
  "Regal Shard" : "Currency",
  "Harbinger's Orb" : "Currency",
  "Harbinger's Shard" : "Currency",
  "Orb of Chance" : "Currency",
  "Orb of Transmutation" : "Currency",
  "Transmutation Shard" : "Currency",
  "Orb of Alchemy" : "Currency",
  "Orb of Binding" : "Currency",
  "Binding Shard" : "Currency",
  "Alchemy Shard" : "Currency",
  "Blacksmith's Whetstone" : "Currency",
  "Clear Oil" : "Currency",
  "Opalescent Oil" : "Currency",
  "Silver Oil" : "Currency",
  "Golden Oil" : "Currency",
  "Sepia Oil" : "Currency",
  "Amber Oil" : "Currency",
  "Verdant Oil" : "Currency",
  "Teal Oil" : "Currency",
  "Azure Oil" : "Currency",
  "Violet Oil" : "Currency",
  "Crimson Oil" : "Currency",
  "Black Oil" : "Currency",
  "Stacked Deck" : "Currency",
  "Imprint" : "Currency",
  "Eternal Orb" : "Currency",
  "Timeless Karui Emblem" : "Map Fragments",
  "Timeless Eternal Empire Emblem" : "Map Fragments",
  "Timeless Vaal Emblem" : "Map Fragments",
  "Timeless Templar Emblem" : "Map Fragments",
  "Timeless Maraketh Emblem" : "Map Fragments",
  "Eber's Key" : "Map Fragments",
  "Inya's Key" : "Map Fragments",
  "Volkuur's Key" : "Map Fragments",
  "Yriel's Key" : "Map Fragments",
  "Sacrifice at Dawn" : "Map Fragments",
  "Sacrifice at Dusk" : "Map Fragments",
  "Sacrifice at Midnight" : "Map Fragments",
  "Sacrifice at Noon" : "Map Fragments",
  "Fragment of the Chimera" : "Map Fragments",
  "Fragment of the Hydra" : "Map Fragments",
  "Fragment of the Minotaur" : "Map Fragments",
  "Fragment of the Phoenix" : "Map Fragments",
  "Mortal Grief" : "Map Fragments",
  "Mortal Hope" : "Map Fragments",
  "Mortal Ignorance" : "Map Fragments",
  "Mortal Rage" : "Map Fragments",
  "Chayula's Breachstone" : "Map Fragments",
  "Chayula's Charged Breachstone" : "Map Fragments",
  "Chayula's Enriched Breachstone" : "Map Fragments",
  "Chayula's Pure Breachstone" : "Map Fragments",
  "Esh's Breachstone" : "Map Fragments",
  "Esh's Charged Breachstone" : "Map Fragments",
  "Esh's Enriched Breachstone" : "Map Fragments",
  "Esh's Pure Breachstone" : "Map Fragments",
  "Tul's Breachstone" : "Map Fragments",
  "Tul's Charged Breachstone" : "Map Fragments",
  "Tul's Enriched Breachstone" : "Map Fragments",
  "Tul's Pure Breachstone" : "Map Fragments",
  "Uul-Netol's Breachstone" : "Map Fragments",
  "Uul-Netol's Charged Breachstone" : "Map Fragments",
  "Uul-Netol's Enriched Breachstone" : "Map Fragments",
  "Uul-Netol's Pure Breachstone" : "Map Fragments",
  "Xoph's Breachstone" : "Map Fragments",
  "Xoph's Charged Breachstone" : "Map Fragments",
  "Xoph's Enriched Breachstone" : "Map Fragments",
  "Xoph's Pure Breachstone" : "Map Fragments",
  "Divine Vessel" : "Map Fragments",
  "Ancient Reliquary Key" : "Misc Map Items",
  "Timeworn Reliquary Key" : "Misc Map Items",
  "Offering to the Goddess" : "Labyrinth Items",
  
  // not actually in the game - pseudo-items for vendor recipe
  "6-socket Items" : "Currency",
  "6-link Items" : "Currency",
  "R-G-B linked Items" : "Currency"
  
};


function getCategory(item) {
  
  var t = item.typeLine;
  
  switch(item.frameType) {
    case 4:
      var n = t.replace("Superior ", "");
      if(gemBaseTypes[n]) {
        return gemBaseTypes[n];
      } else {
        logger.info(`No base type found for gem [${t}]`);
        return null;
      }
    case 5:
      if(otherBaseTypes[t]) {
        return otherBaseTypes[t];
      } else {
        return "Labyrinth Items";
      }
    case 6:
      return "Divination Card";
    case 7:
      return "Quest Items";
    case 8:
      return "Prophecy";
  }
  
  // Maligaro's Map quest item has frameType 7, already detected above as a quest item
  if(t.endsWith("Map")) {
    return "Maps";
  }

  if(t.endsWith("Scarab")) {
    return "Map Fragments";
  }

  if(t.endsWith("Incubator")) {
    return "Incubator";
  }

  if(t.startsWith("Captured Soul")) {
    return "Pantheon Soul";
  }
  
  if(t.endsWith("Piece")) {
    return "Harbinger Item Piece";
  }
  
  if(item.icon.includes("BestiaryOrbFull")) {
    return "Captured Beast";
  }

  if(otherBaseTypes[t]) {
    return otherBaseTypes[t];
  }
  
  // equipment - search by hardcoded basetype
  t = t.replace("Superior ", "");
  
  // non-magic equipment
  if(item.frameType !== 1) {
    if(equipmentBaseTypes[t]) {
      return equipmentBaseTypes[t];
    }
  }
  
  // magic equipment - typeline is polluted by prefixes $%&*#^@!!!
  var keys = Object.keys(equipmentBaseTypes);
  for(var i = 0; i < keys.length; i++) {
    var key = keys[i];
    if(t.includes(key)) {
      return equipmentBaseTypes[key];
    }
  }
  
  logger.info("No category found for item! JSON follows:")
  logger.info(JSON.stringify(item));
  return null;  

}

module.exports.getCategory = getCategory;